import Mathlib.Data.Fin.VecNotation
import Mathlib.Data.Rat.Defs

/-!
# Printed membership-inference validation

Generated by `scripts/memorization_data.py`; do not edit by hand.
arXiv:2505.24832v3, Section 5.2.2, Table 2.
Source: papers/arXiv-2505.24832/tables/table04_scaling_datasets.tex
SHA256: 54fa9d167bf7ff5d6a6ad48a31f9fe47714d45abff2689e3966a66178630a37a
The rational values represent the printed, rounded measurements exactly;
they are not identified with unknown unrounded experimental values.
-/

namespace Transformer.Memorization

/-- Section 5.2.2, Table 2: the observed percentages and uncertainty are
converted to the same unit interval used by the prediction column.
The table calls the 123,702,528-parameter model GPT2-Medium; its actual
parameter count is retained without adopting that inconsistent label. -/
structure MembershipObservation where
  parameters : ℕ
  datasetSize : ℕ
  predicted : ℚ
  observed : ℚ
  uncertainty : ℚ

/-- Section 5.2.2, Table 2: all six reported validation results. -/
def membershipTable : Fin 6 → MembershipObservation := ![
  ⟨1556075200, 170654583, (11 / 20), (5461 / 10000), (13 / 1000)⟩,
  ⟨1556075200, 76795021, (3 / 4), (1777 / 2500), (1 / 250)⟩,
  ⟨1556075200, 18851574, (19 / 20), (1917 / 2000), (1 / 125)⟩,
  ⟨123702528, 13566442, (11 / 20), (334 / 625), (11 / 1000)⟩,
  ⟨123702528, 6104935, (3 / 4), (6569 / 10000), (3 / 500)⟩,
  ⟨123702528, 1498634, (19 / 20), (4899 / 5000), (3 / 1000)⟩]

end Transformer.Memorization
