import Mathlib.Data.Fin.VecNotation
import Mathlib.Data.Rat.Defs

/-!
# Printed model-capacity estimates

Generated by `scripts/memorization_data.py`; do not edit by hand.
arXiv:2505.24832v3, Section 3.2, Table 1.
Source: papers/arXiv-2505.24832/tables/table05_mem_precision.tex
SHA256: 4a862912a8a40db1d5c6b3108d8208c166d382f50c89f554ec6cc0792b09fc8a
The rational values represent the printed, rounded measurements exactly;
they are not identified with unknown unrounded experimental values.
-/

namespace Transformer.Memorization

/-- Section 3.2, Table 1: model configuration and rounded capacity/bpp fields. -/
structure PrecisionObservation where
  layers : ℕ
  width : ℕ
  parameters : ℕ
  fullCapacity : ℕ
  halfCapacity : ℕ
  fullBpp : ℚ
  halfBpp : ℚ

/-- Section 3.2, Table 1: all sixteen model configurations in source order. -/
def precisionTable : Fin 16 → PrecisionObservation := ![
  ⟨1, 32, 80400, 339000, 316000, (423 / 100), (393 / 100)⟩,
  ⟨1, 64, 185000, 727000, 693000, (98 / 25), (187 / 50)⟩,
  ⟨1, 128, 469000, 1710000, 1690000, (73 / 20), (361 / 100)⟩,
  ⟨1, 256, 1330000, 4150000, 3830000, (78 / 25), (72 / 25)⟩,
  ⟨2, 32, 93100, 387000, 331000, (104 / 25), (89 / 25)⟩,
  ⟨2, 64, 235000, 960000, 927000, (102 / 25), (197 / 50)⟩,
  ⟨2, 128, 667000, 2660000, 2600000, (399 / 100), (389 / 100)⟩,
  ⟨2, 256, 2120000, 8490000, 7760000, (401 / 100), (183 / 50)⟩,
  ⟨4, 32, 118000, 465000, 399000, (98 / 25), (337 / 100)⟩,
  ⟨4, 64, 335000, 1340000, 1140000, (199 / 50), (339 / 100)⟩,
  ⟨4, 128, 1060000, 4020000, 3750000, (189 / 50), (353 / 100)⟩,
  ⟨4, 256, 3700000, 13600000, 13000000, (92 / 25), (351 / 100)⟩,
  ⟨8, 32, 169000, 512000, 485000, (151 / 50), (143 / 50)⟩,
  ⟨8, 64, 535000, 2050000, 1710000, (383 / 100), (319 / 100)⟩,
  ⟨8, 128, 1860000, 7230000, 6490000, (389 / 100), (349 / 100)⟩,
  ⟨8, 256, 6860000, 27100000, 25100000, (99 / 25), (73 / 20)⟩]

end Transformer.Memorization
