/-
# RASP: compiling a program to layers and heads

Weiss, Goldberg, Yahav — arXiv:2106.06981v2, "Thinking Like Transformers",
§3.1 ("Compilation") and §4 ("Sandwich Transformers").

The abstract's central claim is that "analyzing a RASP program implies a
maximum number of heads and layers necessary to encode a task in a
transformer".  That needs the *syntax* of a program and not only its value,
so this file adds one: an `Expr` is a RASP s-op as written, and `Expr.eval`
gives it the semantics of `RASP.Defs`.

§3.1 states the compilation rule:

> Each aggregation is an attention head, which must be placed at a layer
> later than all of its inputs.  Elementwise operations are feedforward
> operations, and sit in the earliest layer containing all of their
> dependencies.

`Expr.heads` and `Expr.layers` are that rule read as two counts, and
`layers_lt_agg_*` is the "later than all of its inputs" half of it.  The
counts are upper bounds rather than exact costs, because §3.1 also notes that
"aggregations performed at the same layer with the same selector can be
merged into the same attention head".

A selector is a boolean combination of `select` operations (§3, "selector
manipulations"), which is why an aggregation node carries `m` key/query pairs
with their comparison operators and one boolean function `φ` of the `m` bits:
that is exactly the boolean algebra generated by `m` atomic selectors, and it
keeps the syntax a single inductive type.

§4 draws a consequence of the layer count that is a theorem about programs
and not about transformers: "in RASP, there is little value to repeated
elementwise operations before the first `aggregate`: each position has only
its initial input, and cannot generate new information".  That is
`eval_eq_of_heads_eq_zero`, and `not_reverse_of_heads_eq_zero` is the sharp
form — the smallest program of §3 that no head-free program computes.
-/

import Transformer.RASP.Programs

namespace Transformer
namespace RASP

/-- The syntax of a RASP s-op (§3).

`agg m k q p φ v` is `aggregate(S, v)` for the selector
`S i j = φ (fun a => p a (k a j) (q a i))`, i.e. an arbitrary boolean
combination of the `m` atomic selectors `select (k a) (q a) (p a)`. -/
inductive Expr : Type
  /-- The built-in s-op `tokens`. -/
  | tokens : Expr
  /-- The built-in s-op `indices`. -/
  | indices : Expr
  /-- A constant s-op, broadcast at every position. -/
  | const : ℝ → Expr
  /-- A unary elementwise operation. -/
  | map : (ℝ → ℝ) → Expr → Expr
  /-- A binary elementwise operation. -/
  | zip : (ℝ → ℝ → ℝ) → Expr → Expr → Expr
  /-- `aggregate` over a boolean combination of `m` atomic selectors. -/
  | agg (m : ℕ) (k q : Fin m → Expr) (p : Fin m → ℝ → ℝ → Bool)
      (φ : (Fin m → Bool) → Bool) (v : Expr) : Expr

namespace Expr

/-- The value of a program on an input sequence of length `n`, in the
semantics of `RASP.Defs`. -/
noncomputable def eval {n : ℕ} (x : Seq n ℝ) : Expr → Seq n ℝ
  | .tokens => x
  | .indices => RASP.indices n
  | .const c => fun _ => c
  | .map f e => fun i => f (eval x e i)
  | .zip f a b => fun i => f (eval x a i) (eval x b i)
  | .agg _ k q p φ v =>
      aggregate (fun i j => φ fun a => p a (eval x (k a) j) (eval x (q a) i)) (eval x v) 0

/-- The number of attention heads the program compiles to: one per
aggregation (§3.1).  An upper bound, since aggregations sharing a layer and a
selector may be merged. -/
def heads : Expr → ℕ
  | .tokens | .indices | .const _ => 0
  | .map _ e => heads e
  | .zip _ a b => heads a + heads b
  | .agg m k q _ _ v => (∑ a : Fin m, (heads (k a) + heads (q a))) + heads v + 1

/-- The number of layers the program compiles to: an aggregation sits one
layer above every s-op it reads, and an elementwise operation sits in the
earliest layer holding all of its dependencies (§3.1). -/
def layers : Expr → ℕ
  | .tokens | .indices | .const _ => 0
  | .map _ e => layers e
  | .zip _ a b => max (layers a) (layers b)
  | .agg m k q _ _ v =>
      max (Finset.univ.sup fun a : Fin m => max (layers (k a)) (layers (q a))) (layers v) + 1

/-- **An aggregation sits strictly above the s-op it aggregates.** -/
theorem layers_lt_agg_value {m : ℕ} (k q : Fin m → Expr) (p : Fin m → ℝ → ℝ → Bool)
    (φ : (Fin m → Bool) → Bool) (v : Expr) : v.layers < (Expr.agg m k q p φ v).layers := by
  rw [layers]
  omega

/-- **And strictly above every s-op its selector reads** — keys and queries
alike (§3.1). -/
theorem layers_lt_agg_select {m : ℕ} (k q : Fin m → Expr) (p : Fin m → ℝ → ℝ → Bool)
    (φ : (Fin m → Bool) → Bool) (v : Expr) (a : Fin m) :
    max (k a).layers (q a).layers < (Expr.agg m k q p φ v).layers := by
  have := Finset.le_sup (f := fun a : Fin m => max (layers (k a)) (layers (q a)))
    (Finset.mem_univ a)
  rw [layers]
  omega

/-- **A program never needs more layers than heads.**  Both counts are zero
exactly on the head-free programs, and each layer above the first is opened
by an aggregation of its own. -/
theorem layers_le_heads (e : Expr) : e.layers ≤ e.heads := by
  induction e with
  | tokens | indices | const _ => simp [layers, heads]
  | map _ _ ih => simpa [layers, heads] using ih
  | zip _ _ _ iha ihb => simp only [layers, heads]; omega
  | agg m k q p φ v ihk ihq ihv =>
      simp only [layers, heads]
      have hsup : (Finset.univ.sup fun a : Fin m => max (layers (k a)) (layers (q a)))
          ≤ ∑ a : Fin m, ((k a).heads + (q a).heads) := by
        refine Finset.sup_le fun a _ => ?_
        have hmem := Finset.single_le_sum
          (f := fun a : Fin m => (k a).heads + (q a).heads) (fun a _ => Nat.zero_le _)
          (Finset.mem_univ a)
        have := ihk a
        have := ihq a
        omega
      omega

/-- **Head-free programs are pointwise.**  §4: "in RASP, there is little
value to repeated elementwise operations before the first `aggregate`: each
position has only its initial input, and cannot generate new information."
Formally, a program that compiles to no attention head has a value at
position `i` that depends on the input only through the token at `i`. -/
theorem eval_eq_of_heads_eq_zero {n : ℕ} (x y : Seq n ℝ) (i : Fin n) (hxy : x i = y i)
    (e : Expr) (h : e.heads = 0) : e.eval x i = e.eval y i := by
  induction e with
  | tokens => exact hxy
  | indices => rfl
  | const c => rfl
  | map f e ih =>
      simp only [eval]
      rw [ih (by simpa [heads] using h)]
  | zip f a b iha ihb =>
      rw [heads] at h
      simp only [eval]
      rw [iha (by omega), ihb (by omega)]
  | agg m k q p φ v ihk ihq ihv => exact absurd h (by rw [heads]; omega)

/-- **One head is necessary.**  `reverse`, the one-line program of §3, is
computed by no head-free program: two inputs agreeing at position `0` have
different reversals there, and a head-free program cannot tell them apart. -/
theorem not_reverse_of_heads_eq_zero (e : Expr) (h : e.heads = 0) :
    ¬ ∀ x : Seq 2 ℝ, e.eval x = reverse x (0 : ℝ) := by
  intro hrev
  have hx : e.eval (![0, 1] : Seq 2 ℝ) 0 = e.eval (![0, 0] : Seq 2 ℝ) 0 :=
    eval_eq_of_heads_eq_zero (![0, 1] : Seq 2 ℝ) (![0, 0] : Seq 2 ℝ) 0 (by norm_num) e h
  rw [hrev, hrev, reverse_apply, reverse_apply, show (0 : Fin 2).rev = 1 from rfl] at hx
  norm_num at hx

/-- The counts are not vacuous, and they reproduce the paper's own reading of
`reverse`.  Figure 11's caption: "This compiles to an architecture with two
layers: `length` requires an attention head to compute, and `reverse` applies
a select-aggregate pair that uses (among others) the s-op `length`."  Written
out — with `length` as the program §3.1 gives for it — that is exactly two
heads and two layers.  The elementwise program below it has none, so the
hypothesis `heads = 0` is satisfiable too. -/
example :
    let lengthProg : Expr :=
      Expr.map (fun z => 1 / z)
        (Expr.agg 1 (fun _ => Expr.const 1) (fun _ => Expr.const 1)
          (fun _ a b => decide (a = b)) (fun bs => bs 0)
          (Expr.map (fun z => if z = 0 then 1 else 0) Expr.indices))
    let revProg : Expr :=
      Expr.agg 1 (fun _ => Expr.indices)
        (fun _ => Expr.zip (fun l z => l - z - 1) lengthProg Expr.indices)
        (fun _ a b => decide (a = b)) (fun bs => bs 0) Expr.tokens
    revProg.heads = 2 ∧ revProg.layers = 2 ∧
      (Expr.map (fun t => t + 1) Expr.tokens).heads = 0 := by
  refine ⟨by simp [Expr.heads], by simp [Expr.layers], by simp [Expr.heads]⟩

end Expr

end RASP
end Transformer
