/-
# Causal attention — Single-token dynamics (§3 of 2411.04990v2)

* `Lemma lemma1` — convergence of the single-token ODE `ẋ = Proj_x (Vx)`:
   * exponential convergence to `L'`,
   * linear convergence to `L`,
where `L'` is the span of all generalized eigenvectors associated to
eigenvalues with maximal real part, and `L ⊆ L'` is generated by the
eigenvectors with the largest corresponding Jordan block.
-/

import Transformer.Basic
import Transformer.Causal.Basic

open scoped BigOperators
open Real

namespace Transformer
namespace Causal

open Causal

variable (d : ℕ)

/-- **Lemma (lemma1).** *Single-token convergence.*

For almost any `x(0) ∈ 𝕊^{d-1}`, the unique solution of
`ẋ(t) = Proj_{x(t)} (V x(t))` satisfies:

  (i) `dist(x(t), L'(V) ∩ 𝕊^{d-1}) ≤ C e^{-c t}` (exponential),

 (ii) `dist(x(t), L(V) ∩ 𝕊^{d-1}) ≤ c / t` (linear in `1/t`),

where `L'(V)` is spanned by the generalized eigenvectors of `V` whose
eigenvalue has maximal real part, and `L(V) ⊆ L'(V)` by the eigenvectors
sitting in the largest Jordan block.

The two subspaces are existentially quantified rather than constructed: what
the statement keeps of them is what the proof uses — that they are `V`-invariant
and nested — since the real Jordan decomposition behind their definition is not
available here.  "Almost any `x(0)`" is the complement of a proper subspace
`E` of `ℝ^d`, which is what the survey's exceptional set is.

Not proved here.

Source: arXiv:2411.04990v2, §3, `lemma1`. -/
theorem single_token_convergence (V : ParamMatrix d) :
    ∃ (Lprime Lmain E : Submodule ℝ (EucSpace d)) (C c : ℝ),
      Lmain ≤ Lprime ∧ E ≠ ⊤ ∧ 0 < C ∧ 0 < c ∧
      (∀ y ∈ Lprime, V y ∈ Lprime) ∧ (∀ y ∈ Lmain, V y ∈ Lmain) ∧
      ∀ x : ℝ → EucSpace d, Causal.singleTokenODE d V x → ‖x 0‖ = 1 → x 0 ∉ E →
        (∀ t : ℝ, 0 ≤ t →
          Metric.infDist (x t)
              ((Lprime : Set (EucSpace d)) ∩ Metric.sphere (0 : EucSpace d) 1)
            ≤ C * Real.exp (-(c * t))) ∧
        (∀ t : ℝ, 0 < t →
          Metric.infDist (x t)
              ((Lmain : Set (EucSpace d)) ∩ Metric.sphere (0 : EucSpace d) 1)
            ≤ C / t) := by
  sorry

end Causal
end Transformer
