/-
# Causal attention — Single-token dynamics (§3 of 2411.04990v2)

* `Lemma lemma1` — convergence of the single-token ODE `ẋ = Proj_x (Vx)`:
   * exponential convergence to `L'`,
   * linear convergence to `L`,
where `L'` is the span of all generalized eigenvectors associated to
eigenvalues with maximal real part, and `L ⊆ L'` is generated by the
eigenvectors with the largest corresponding Jordan block.
-/

import Transformer.Basic
import Transformer.Causal.Basic

open scoped BigOperators
open Real

namespace Transformer
namespace CausalSingleToken

open Causal

variable (d : ℕ)

/-- The eigenspace `L'(V) := span of eigenvectors of `V` with eigenvalue real
part equal to `λ_max(V)`. -/
noncomputable def L_prime (V : ParamMatrix d) : Submodule ℝ (EucSpace d) := by
  exact ⊥  -- abstract: span of generalized eigenvectors.

/-- The subspace `L(V) ⊆ L'(V)` generated by eigenvectors with the largest
corresponding Jordan block. -/
noncomputable def L_main (V : ParamMatrix d) : Submodule ℝ (EucSpace d) := by
  exact ⊥  -- abstract.

/-- **Lemma (lemma1).** *Single-token convergence.*

For almost any `x(0) ∈ 𝕊^{d-1}`, the unique solution of
`ẋ(t) = Proj_{x(t)} (V x(t))` satisfies:

  (i) `dist(x(t), L'(V) ∩ 𝕊^{d-1}) ≤ C e^{-c t}` (exponential),

 (ii) `dist(x(t), L(V) ∩ 𝕊^{d-1}) ≤ c / t` (linear in `1/t`). -/
theorem single_token_convergence
    (V : ParamMatrix d) (x : ℝ → EucSpace d)
    (hX : Causal.singleTokenODE d V x) :
    ∃ (C c : ℝ), 0 < C ∧ 0 < c ∧
      ∀ t : ℝ, 0 ≤ t →
        ‖x t‖ ≤ C * Real.exp (-(c * t)) := by
  sorry

end CausalSingleToken
end Transformer
