//! Reading the schedule plan.
//!
//! `plan.yaml` is generated by the MILP scheduler (`yaml.dump`, block
//! mappings, flow sequences, width 120) and read back by
//! `model/weights.py::_load_plan`.  Only that shape is accepted here: a block
//! mapping of integers and flow sequences, two-space indented.  Anything else
//! is an error rather than a guess — the file is machine-written, so a
//! surprise in it is a bug somewhere, not a dialect to accommodate.
//!
//! Every entry names dimensions *by name*, which is why the port reproduces
//! `auto_name` exactly.

use std::collections::HashMap;

use crate::expr::DimId;
use crate::graph::{DimData, Graph, LookUpId};

/// One transformer layer's schedule.
#[derive(Clone, Debug, Default)]
pub struct LayerPlan {
    pub layer: usize,
    /// Lookups read in this layer's attention half, first appearance first.
    pub attention: Vec<LookUpId>,
    pub persist1: Vec<DimId>,
    pub ffn: Vec<DimId>,
    pub persist2: Vec<DimId>,
    /// Dimensions alive after the attention half, if the plan states them.
    pub after_persist1: Option<Vec<DimId>>,
    /// Dimensions alive after the FFN half, if the plan states them.
    pub after_persist2: Option<Vec<DimId>>,
}

#[derive(Clone, Debug)]
pub struct Plan {
    pub n_layers: usize,
    pub layers: Vec<LayerPlan>,
}

// ── The reader ──────────────────────────────────────────────────────

/// A scalar or a flow sequence, which is all this document holds.
#[derive(Debug)]
enum Value {
    Scalar(String),
    Seq(Vec<String>),
}

struct Reader<'a> {
    lines: Vec<&'a str>,
    at: usize,
}

fn unquote(s: &str) -> String {
    let s = s.trim();
    if s.len() >= 2 && s.starts_with('\'') && s.ends_with('\'') {
        s[1..s.len() - 1].replace("''", "'")
    } else if s.len() >= 2 && s.starts_with('"') && s.ends_with('"') {
        s[1..s.len() - 1].to_string()
    } else {
        s.to_string()
    }
}

/// Split a flow sequence body on commas that are not inside quotes.
fn split_flow(body: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut quote: Option<char> = None;
    for ch in body.chars() {
        match quote {
            Some(q) => {
                cur.push(ch);
                if ch == q {
                    quote = None;
                }
            }
            None => match ch {
                '\'' | '"' => {
                    quote = Some(ch);
                    cur.push(ch);
                }
                ',' => {
                    out.push(std::mem::take(&mut cur));
                }
                _ => cur.push(ch),
            },
        }
    }
    if !cur.trim().is_empty() {
        out.push(cur);
    }
    out.into_iter().map(|s| unquote(&s)).filter(|s| !s.is_empty()).collect()
}

impl<'a> Reader<'a> {
    fn new(text: &'a str) -> Self {
        let lines = text
            .lines()
            .filter(|l| !l.trim().is_empty() && !l.trim_start().starts_with('#'))
            .collect();
        Reader { lines, at: 0 }
    }

    fn peek(&self) -> Option<&'a str> {
        self.lines.get(self.at).copied()
    }

    fn indent(line: &str) -> usize {
        line.len() - line.trim_start().len()
    }

    /// Read the value that follows `key:` on `rest`, continuing onto the
    /// following lines while a flow sequence is still open.
    fn value(&mut self, rest: &str) -> Result<Option<Value>, String> {
        let rest = rest.trim();
        if rest.is_empty() {
            return Ok(None); // a nested block mapping follows
        }
        if let Some(body) = rest.strip_prefix('[') {
            let mut body = body.to_string();
            while !body.contains(']') {
                self.at += 1;
                let more = self.peek().ok_or("unterminated flow sequence")?;
                body.push(' ');
                body.push_str(more.trim());
            }
            let end = body.rfind(']').ok_or("unterminated flow sequence")?;
            return Ok(Some(Value::Seq(split_flow(&body[..end]))));
        }
        Ok(Some(Value::Scalar(unquote(rest))))
    }

    /// Read a block mapping at the given indentation into `(key, value)`
    /// pairs, recursing into nested mappings by prefixing `parent.child`.
    fn mapping(&mut self, indent: usize, prefix: &str, out: &mut Vec<(String, Value)>) -> Result<(), String> {
        while let Some(line) = self.peek() {
            let ind = Self::indent(line);
            if ind < indent || line.trim_start().starts_with("- ") && ind <= indent && !prefix.is_empty() {
                break;
            }
            if ind > indent {
                return Err(format!("unexpected indent: {line:?}"));
            }
            if line.trim_start().starts_with('-') {
                break;
            }
            let body = line.trim_start();
            let colon = body.find(':').ok_or_else(|| format!("no key in {body:?}"))?;
            let key = body[..colon].trim().to_string();
            let full = if prefix.is_empty() { key.clone() } else { format!("{prefix}.{key}") };
            match self.value(&body[colon + 1..])? {
                Some(v) => {
                    out.push((full, v));
                    self.at += 1;
                }
                None => {
                    self.at += 1;
                    let child = match self.peek() {
                        Some(l) => Self::indent(l),
                        None => break,
                    };
                    if child > indent {
                        self.mapping(child, &full, out)?;
                    }
                }
            }
        }
        Ok(())
    }
}

fn seq<'a>(fields: &'a [(String, Value)], key: &str) -> Option<&'a [String]> {
    fields.iter().find(|(k, _)| k == key).and_then(|(_, v)| match v {
        Value::Seq(s) => Some(s.as_slice()),
        Value::Scalar(_) => None,
    })
}

fn scalar<'a>(fields: &'a [(String, Value)], key: &str) -> Option<&'a str> {
    fields.iter().find(|(k, _)| k == key).and_then(|(_, v)| match v {
        Value::Scalar(s) => Some(s.as_str()),
        Value::Seq(_) => None,
    })
}

// ── Resolution against a graph ──────────────────────────────────────

impl Plan {
    /// Parse a plan and resolve every name against the graph it was scheduled
    /// for.  An unknown name is an error: it means the two sides disagree
    /// about the graph, which is the failure mode worth catching loudly.
    pub fn load(text: &str, g: &Graph) -> Result<Plan, String> {
        let mut by_name: HashMap<&str, DimId> = HashMap::new();
        for dim in &g.dims {
            by_name.insert(dim.name.as_str(), dim.id);
        }
        let resolve = |name: &str| -> Result<DimId, String> {
            by_name.get(name).copied().ok_or_else(|| format!("plan names unknown dim '{name}'"))
        };
        let resolve_all = |names: &[String]| -> Result<Vec<DimId>, String> {
            names.iter().map(|n| resolve(n)).collect()
        };

        let mut r = Reader::new(text);
        let mut top: Vec<(String, Value)> = Vec::new();
        // `summary:` first, then `layers:` as a block sequence.
        let mut n_layers = 0usize;
        let mut layers: Vec<LayerPlan> = Vec::new();

        while let Some(line) = r.peek() {
            let body = line.trim_start();
            if body.starts_with("- ") {
                // one layer entry
                let indent = Reader::indent(line);
                let mut fields: Vec<(String, Value)> = Vec::new();
                // rewrite the "- " into spaces so the entry reads as a mapping
                let mut first = line.replacen('-', " ", 1).to_string();
                let entry_indent = first.len() - first.trim_start().len();
                loop {
                    let trimmed = first.trim_start().to_string();
                    let colon = trimmed.find(':').ok_or("layer entry without a key")?;
                    let key = trimmed[..colon].trim().to_string();
                    match r.value(&trimmed[colon + 1..])? {
                        Some(v) => {
                            fields.push((key, v));
                            r.at += 1;
                        }
                        None => {
                            r.at += 1;
                            let child = match r.peek() {
                                Some(l) => Reader::indent(l),
                                None => break,
                            };
                            if child > entry_indent {
                                r.mapping(child, &key, &mut fields)?;
                            }
                        }
                    }
                    match r.peek() {
                        Some(l)
                            if Reader::indent(l) == entry_indent
                                && !l.trim_start().starts_with('-') =>
                        {
                            first = l.to_string();
                        }
                        _ => break,
                    }
                }
                let _ = indent;

                let layer: usize = scalar(&fields, "layer")
                    .ok_or("layer entry without a layer index")?
                    .parse()
                    .map_err(|e| format!("bad layer index: {e}"))?;

                let attention = seq(&fields, "attention").unwrap_or(&[]);
                let mut seen: Vec<LookUpId> = Vec::new();
                for name in attention {
                    let d = resolve(name)?;
                    match g.dim(d).data {
                        DimData::LookUp { lookup, .. } => {
                            if !seen.contains(&lookup) {
                                seen.push(lookup);
                            }
                        }
                        _ => return Err(format!("{name} is scheduled for attention but is not a lookup")),
                    }
                }

                layers.push(LayerPlan {
                    layer,
                    attention: seen,
                    persist1: resolve_all(seq(&fields, "persist1").unwrap_or(&[]))?,
                    ffn: resolve_all(seq(&fields, "ffn").unwrap_or(&[]))?,
                    persist2: resolve_all(seq(&fields, "persist2").unwrap_or(&[]))?,
                    after_persist1: seq(&fields, "after_persist1.dims")
                        .map(resolve_all)
                        .transpose()?,
                    after_persist2: seq(&fields, "after_persist2.dims")
                        .map(resolve_all)
                        .transpose()?,
                });
                continue;
            }

            let before = r.at;
            r.mapping(Reader::indent(line), "", &mut top)?;
            if let Some(v) = scalar(&top, "summary.layers") {
                n_layers = v.parse().map_err(|e| format!("bad summary.layers: {e}"))?;
            }
            if r.at == before {
                r.at += 1;
            }
        }

        if n_layers == 0 {
            return Err("plan has no summary.layers".into());
        }
        Ok(Plan { n_layers, layers })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::interpreter;

    #[test]
    fn a_flow_sequence_survives_a_line_break_and_a_quoted_bracket() {
        let items = split_flow("a, 'store_bytes[0]', b+1,\n      c");
        assert_eq!(items, vec!["a", "store_bytes[0]", "b+1", "c"]);
    }

    /// The released schedule, against the graph this crate builds.  The plan
    /// is an input and is compiled in, so this cannot skip.
    #[test]
    fn the_released_plan_resolves_against_the_ported_graph() {
        let mg = interpreter::build();
        let plan = Plan::load(crate::release::PLAN, &mg.graph).expect("plan.yaml resolves");
        assert_eq!(plan.n_layers, 7);
        assert_eq!(plan.layers.len(), 7);
        let l0 = &plan.layers[0];
        assert_eq!(l0.attention, vec![0, 1, 2, 3, 4]);
        assert_eq!(l0.ffn.len(), 10);
        assert_eq!(
            mg.graph.name_of(l0.ffn[0]),
            "unsigned_branch+",
            "the plan resolves by name, so this is also a check on auto_name"
        );
        assert_eq!(l0.after_persist1.as_ref().unwrap().len(), 20);
        let l5 = &plan.layers[5];
        assert!(l5.attention.is_empty(), "layer 5 does no attention");
        assert_eq!(l5.ffn.len(), 33);
    }
}
