"""Execution and persistence interfaces used by benchmark orchestration."""

from typing import Protocol

from ..domain.benchmark import Job, ModelConfig
from ..domain.stopping import StopConfig


class Training(Protocol):
    def preflight(self) -> dict: ...
    def dataset_info(self) -> dict: ...
    def environment(self) -> dict: ...
    def configure(self, model: ModelConfig, batch: int, stopping: StopConfig) -> None: ...
    def run(self, job: Job, artifacts: str) -> dict: ...
    def validate(self, row: dict) -> dict: ...


class Results(Protocol):
    def reference_rates(self) -> dict: ...
    def source_context(self) -> dict: ...
    def preflight_result(self, report: dict) -> None: ...
    def prepare(self, protocol: dict) -> list[dict]: ...
    def load(self) -> tuple[dict, list[dict]]: ...
    def artifact_directory(self) -> str: ...
    def append(self, row: dict) -> None: ...
    def report(self, rows: list[dict], seeds: list[int]) -> None: ...
    def validation(self, result: dict) -> None: ...
    def progress(self, message: str) -> None: ...
