/-
Formalization of:
  Geshkovski, Letrouit, Polyanskiy, Rigollet,
  "The emergence of clusters in self-attention dynamics",
  arXiv:2305.05465v6.
-/

import Transformer.Clusters.Section1_Dynamics
import Transformer.Clusters.Section2_LowRank
import Transformer.Clusters.Section3_Rescaled
import Transformer.Clusters.Section3_Discrete
import Transformer.Clusters.Section3_IdCase
import Transformer.Clusters.Section4_Hyperplanes
import Transformer.Clusters.Section4_Codim
import Transformer.Clusters.Section5_Mix
import Transformer.Clusters.Section6_WellPosed
import Transformer.Clusters.Section6_Kernel
import Transformer.Clusters.Section6_KernelDeriv
import Transformer.Clusters.Section6_KernelLip
import Transformer.Clusters.Section6_ContEq
import Transformer.Clusters.Section7_HigherDim
import Transformer.Clusters.Section7_LogSumExp
import Transformer.Clusters.Section7_DistNonDec
import Transformer.Clusters.Section7_Unbounded
import Transformer.Clusters.Section7_Drift
import Transformer.Clusters.Section7_Auxiliary
import Transformer.Clusters.Section7_UnboundedParticles
import Transformer.Clusters.Section7_DriftAverage
import Transformer.Clusters.Section7_ExactAsymptotic
import Transformer.Clusters.Section7_Symmetric
import Transformer.Clusters.Section7_OnlyOneDrift
import Transformer.Clusters.Section7_OnlyOneEscape
import Transformer.Clusters.Section7_OnlyOneCore
import Transformer.Clusters.Section7_OnlyOneSpread
import Transformer.Clusters.Section7_OnlyOne
import Transformer.Clusters.Section7_Bounded
import Transformer.Clusters.Section9_Eigen
import Transformer.Clusters.Extremum
import Transformer.Clusters.Section9_Fj
import Transformer.Clusters.Section9_Limits
import Transformer.Clusters.Section9_Growth
import Transformer.Clusters.Section9_Hyperplanes
import Transformer.Clusters.Section8_Polytope
import Transformer.Clusters.Section8_Origin
import Transformer.Clusters.Section8_Bounded
import Transformer.Clusters.Section8_Energy
import Transformer.Clusters.Section8_Stationary
import Transformer.Clusters.Section10_ProjHull
import Transformer.Clusters.Section10_Remainder
import Transformer.Clusters.Section10_RemainderFalse
import Transformer.Clusters.Section10_Step2
import Transformer.Clusters.Section12_MultiHead
import Transformer.Clusters.Section12_Generic
import Transformer.Clusters.Section12_Feedforward
