import Transformer.Grokking.CircuitEfficiency.SectionC_NativeRecurrence

/-!
# Retained moments of the actual closed clipped CE path

Sources: Varma et al., arXiv:2309.02390v1, appendix C product CE;
PyTorch 2.14.1 native AdamW and clip_grad_norm_ at lab commit dd5680d.
Connect each actual buffer and clock to the previously proved causal
moment history of gradients generated by the current four parameters.
The input sequence is an output of the closed trajectory, not an
arbitrarily prescribed future gradient or a convergence premise.

Clipping supplies the coordinate bounds on every visited state, hence
the corrected moments and epsilon-floor direction estimates now apply
to this actual exact-real path. These bounds do not imply descent at a
prescribed rate or later held-out margin crossing. The fixed reference
tables, plain CE/decoupled-decay deviation and missing numerical-kernel
and learned-GPTMini bridges remain as in NativeRecurrence.
-/

namespace Transformer.Grokking.CircuitEfficiency

open Transformer.Grokking.AdamW

/-- A coordinate's applied gradient, generated from the current closed
CE state at each clock. Source: appendix C product logits with native
AdamW/clipping at dd5680d, actual seeded parameters and retained state. -/
noncomputable def nativeGeneratedGradient (remaining : ℕ) (bound b1 b2 eps decay rate : ℝ)
    (parameters : (ℝ × ℝ) × (ℝ × ℝ)) (i : Fin 4) : ℕ → ℝ :=
  fun k => appliedNativeSubweightGradient remaining bound (nativeSubweightPath remaining
    bound b1 b2 eps decay rate (seededNativeSubweights parameters) k) i

/-- Seeded coordinates retain exactly the number of completed native
updates. Source: PyTorch 2.14.1 AdamW at dd5680d; every derivative,
including zero, is supplied and no per-coordinate step is skipped. -/
theorem native_seeded_path_clock (remaining : ℕ) (bound b1 b2 eps decay rate : ℝ)
    (parameters : (ℝ × ℝ) × (ℝ × ℝ)) (n : ℕ) (i : Fin 4) :
    (nativeSubweightPath remaining bound b1 b2 eps decay rate
      (seededNativeSubweights parameters) n i).clock = n := by
  have hc := native_path_clocks remaining bound b1 b2 eps decay rate
    (seededNativeSubweights parameters) n i
  fin_cases i <;> simpa [seededNativeSubweights, seededScalarState] using hc

/-- Actual retained buffers equal their causal histories of actual
generated clipped CE gradients. Source: native AdamW at dd5680d,
zero initial buffers and the checked closed four-factor recurrence. -/
theorem native_seeded_path_buffers (remaining : ℕ) (bound b1 b2 eps decay rate : ℝ)
    (parameters : (ℝ × ℝ) × (ℝ × ℝ)) (n : ℕ) (i : Fin 4) :
    let state := nativeSubweightPath remaining bound b1 b2 eps decay rate
      (seededNativeSubweights parameters) n i
    let gradient := nativeGeneratedGradient remaining bound b1 b2 eps decay rate parameters i
    state.moment = firstMomentAt b1 gradient n ∧ state.variance = secondMomentAt b2 gradient n := by
  induction n with
  | zero =>
    fin_cases i <;> simp [nativeSubweightPath, seededNativeSubweights,
      seededScalarState, firstMomentAt, secondMomentAt, momentAt]
  | succ n ih =>
    change b1 * _ + (1 - b1) * _ = firstMomentAt b1 _ (n + 1) ∧
      b2 * _ + (1 - b2) * _ ^ 2 = secondMomentAt b2 _ (n + 1)
    rw [ih.1, ih.2]
    exact ⟨rfl, rfl⟩

/-- The actual next retained-buffer direction is precisely the
corrected generated history at its new clock. Source: native AdamW
at dd5680d; no independently initialized or reset optimizer is used. -/
theorem native_path_next_direction (remaining : ℕ) (bound b1 b2 eps decay rate : ℝ)
    (parameters : (ℝ × ℝ) × (ℝ × ℝ)) (n : ℕ) (i : Fin 4) :
    let state := nativeSubweightPath remaining bound b1 b2 eps decay rate
      (seededNativeSubweights parameters) n i
    let gradient := nativeGeneratedGradient remaining bound b1 b2 eps decay rate parameters i
    nextBufferDirection b1 b2 eps state.moment state.variance (gradient n) state.clock =
      historyDirection b1 b2 eps gradient (n + 1) := by
  dsimp only
  have hm := native_seeded_path_buffers remaining bound b1 b2 eps decay rate parameters n i
  rw [hm.1, hm.2, native_seeded_path_clock]
  exact (history_direction_succ b1 b2 eps _ n).symm

/-- The next actual parameter uses that same generated corrected
history, separately from parameter-wise decay. Source: native AdamW
at dd5680d, closing the parameter-to-gradient-to-buffer feedback. -/
theorem native_path_parameter_history (remaining : ℕ) (bound b1 b2 eps decay rate : ℝ)
    (parameters : (ℝ × ℝ) × (ℝ × ℝ)) (n : ℕ) (i : Fin 4) :
    (nativeSubweightPath remaining bound b1 b2 eps decay rate
      (seededNativeSubweights parameters) (n + 1) i).parameter =
      (1 - rate * decay) * (nativeSubweightPath remaining bound b1 b2 eps decay rate
        (seededNativeSubweights parameters) n i).parameter - rate * historyDirection b1 b2 eps
          (nativeGeneratedGradient remaining bound b1 b2 eps decay rate parameters i) (n + 1) := by
  change (1 - rate * decay) * _ - rate * nextBufferDirection b1 b2 eps _ _
    (nativeGeneratedGradient remaining bound b1 b2 eps decay rate parameters i n) _ = _
  rw [native_path_next_direction]

/-- Every actual generated coordinate satisfies the bound from the
shared wrapper. Source: clip_grad_norm_ at dd5680d; no bound on raw
CE derivatives or only on an independently chosen gradient is assumed. -/
theorem native_generated_gradient_abs_bound (remaining : ℕ) (bound b1 b2 eps decay rate : ℝ)
    (parameters : (ℝ × ℝ) × (ℝ × ℝ)) (n : ℕ) (i : Fin 4) (hclip : 0 < bound) :
    |nativeGeneratedGradient remaining bound b1 b2 eps decay rate parameters i n| ≤ bound := by
  exact native_applied_gradient_abs_bound remaining bound _ i hclip

example : (0 : ℝ) < 1 := by norm_num

/-- The actual bias-corrected first moment stays within the wrapper
bound at every positive clock. Source: native AdamW/clipping at
dd5680d; the causal prefix bound is now derived from visited CE states. -/
theorem native_corrected_first_bound (remaining : ℕ) (bound b1 b2 eps decay rate : ℝ)
    (parameters : (ℝ × ℝ) × (ℝ × ℝ)) (n : ℕ) (i : Fin 4)
    (hclip : 0 < bound) (hb : 0 ≤ b1) (h1 : b1 < 1) (hn : 0 < n) :
    let state := nativeSubweightPath remaining bound b1 b2 eps decay rate
      (seededNativeSubweights parameters) n i
    |state.moment / (1 - b1 ^ state.clock)| ≤ bound := by
  dsimp only
  rw [(native_seeded_path_buffers remaining bound b1 b2 eps decay rate parameters n i).1,
    native_seeded_path_clock]
  exact corrected_first_prefix_abs_bound b1 bound _ n hb h1 hn
    (fun k _ => native_generated_gradient_abs_bound remaining bound b1 b2 eps decay rate parameters k i hclip)

example : (0 : ℝ) < 1 ∧ 0 ≤ (9 / 10 : ℝ) ∧ (9 / 10 : ℝ) < 1 ∧ 0 < (3 : ℕ) := by norm_num

/-- Physical corrected variance and its squared wrapper bound hold
for actual retained buffers. Source: native AdamW at dd5680d, squared
input recurrence and the actual positive-clock bias correction. -/
theorem native_corrected_second_bound (remaining : ℕ) (bound b1 b2 eps decay rate : ℝ)
    (parameters : (ℝ × ℝ) × (ℝ × ℝ)) (n : ℕ) (i : Fin 4)
    (hclip : 0 < bound) (hb : 0 ≤ b2) (h1 : b2 < 1) (hn : 0 < n) :
    let state := nativeSubweightPath remaining bound b1 b2 eps decay rate
      (seededNativeSubweights parameters) n i
    0 ≤ state.variance / (1 - b2 ^ state.clock) ∧
      state.variance / (1 - b2 ^ state.clock) ≤ bound ^ 2 := by
  dsimp only
  rw [(native_seeded_path_buffers remaining bound b1 b2 eps decay rate parameters n i).2,
    native_seeded_path_clock]
  exact corrected_second_prefix_bound b2 bound _ n hb h1 hn
    (fun k _ => native_generated_gradient_abs_bound remaining bound b1 b2 eps decay rate parameters k i hclip)

example : (0 : ℝ) < 1 ∧ 0 ≤ (49 / 50 : ℝ) ∧ (49 / 50 : ℝ) < 1 ∧ 0 < (3 : ℕ) := by norm_num

/-- The actual next adaptive direction has an epsilon-floor bound
derived on its closed CE history. Source: native AdamW at dd5680d;
the loose bound can be large and is not a generalization certificate. -/
theorem native_next_direction_abs_bound (remaining : ℕ) (bound b1 b2 eps decay rate : ℝ)
    (parameters : (ℝ × ℝ) × (ℝ × ℝ)) (n : ℕ) (i : Fin 4)
    (hclip : 0 < bound) (hb : 0 ≤ b1) (h1 : b1 < 1) (he : 0 < eps) :
    let state := nativeSubweightPath remaining bound b1 b2 eps decay rate
      (seededNativeSubweights parameters) n i
    |nextBufferDirection b1 b2 eps state.moment state.variance
      (nativeGeneratedGradient remaining bound b1 b2 eps decay rate parameters i n) state.clock| ≤ bound / eps := by
  dsimp only
  rw [native_path_next_direction]
  exact history_direction_prefix_abs_bound b1 b2 eps bound _ (n + 1) hb h1 he (by omega)
    (fun k _ => native_generated_gradient_abs_bound remaining bound b1 b2 eps decay rate parameters k i hclip)

example : (0 : ℝ) < 1 ∧ 0 ≤ (9 / 10 : ℝ) ∧ (9 / 10 : ℝ) < 1 ∧ (0 : ℝ) < 1 / 100000000 := by norm_num

end Transformer.Grokking.CircuitEfficiency
