/-
# Real analytic germs: Division

Adapted from Bochao Kong's LocalComplexGeometry, revision
029697242294aea7989bf5d391199696a43490df, WPTBridge/GermDivision.lean.
The coefficient field and analytic germs are real. Only the required
dependency closure is retained. Apache-2.0 license:
third_party/LocalComplexGeometry/LICENSE.
-/

import Transformer.RealAnalyticGerms.DivisionMaps
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Ideal.Span

open Filter
open scoped BigOperators Topology

noncomputable section
namespace Transformer.RealAnalyticGerms

open Transformer.AnalyticPreparation

/-- Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
theorem preparedGermDivisionRemainder_eq_zero_iff {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (h : AnalyticGerm (n + 1)) :
    preparedGermDivisionRemainder a ha ha0 h = 0 ↔
      ∃ q : AnalyticGerm (n + 1),
        h = q * preparedPolynomialGerm a ha := by
  constructor
  · intro hremainder
    refine ⟨preparedGermDivisionQuotient a ha ha0 h, ?_⟩
    have hspec := preparedGermDivision_spec a ha ha0 h
    unfold IsPreparedGermDivision at hspec
    rw [hremainder, remainderPolynomialGerm_zero, add_zero] at hspec
    exact hspec
  · rintro ⟨q, hq⟩
    have hdivision : IsPreparedGermDivision a ha h q
        (0 : Fin d → AnalyticGerm n) := by
      unfold IsPreparedGermDivision
      rw [hq, remainderPolynomialGerm_zero, add_zero]
    exact (preparedGermDivision_eq_of_isDivision a ha ha0 h q 0 hdivision).2

/-- Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
theorem preparedGermDivisionRemainder_eq_zero_iff_mem_span {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (h : AnalyticGerm (n + 1)) :
    preparedGermDivisionRemainder a ha ha0 h = 0 ↔
      h ∈ Ideal.span ({preparedPolynomialGerm a ha} :
        Set (AnalyticGerm (n + 1))) := by
  rw [preparedGermDivisionRemainder_eq_zero_iff a ha ha0 h,
    Ideal.mem_span_singleton']
  constructor
  · rintro ⟨q, hq⟩
    exact ⟨q, hq.symm⟩
  · rintro ⟨q, hq⟩
    exact ⟨q, hq.symm⟩

/-- The exact kernel statement needed by Rückert's remainder-module
induction: the kernel is the principal ideal generated by the prepared
polynomial, viewed as a module over lower-dimensional germs.
Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
theorem preparedGermDivisionRemainderLinearMap_ker {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    LinearMap.ker (preparedGermDivisionRemainderLinearMap a ha ha0) =
      (Ideal.span ({preparedPolynomialGerm a ha} :
        Set (AnalyticGerm (n + 1)))).restrictScalars (AnalyticGerm n) := by
  ext h
  change preparedGermDivisionRemainder a ha ha0 h = 0 ↔
    h ∈ Ideal.span ({preparedPolynomialGerm a ha} :
      Set (AnalyticGerm (n + 1)))
  exact preparedGermDivisionRemainder_eq_zero_iff_mem_span a ha ha0 h

/-- Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
theorem preparedGermDivisionRemainderLinearMap_ker_le {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    LinearMap.ker (preparedGermDivisionRemainderLinearMap a ha ha0) ≤
      (Ideal.span ({preparedPolynomialGerm a ha} :
        Set (AnalyticGerm (n + 1)))).restrictScalars (AnalyticGerm n) :=
  (preparedGermDivisionRemainderLinearMap_ker a ha ha0).le

/-- Every coefficient vector already is the remainder of its degree-`< d`
polynomial germ.
Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
theorem preparedGermDivisionRemainderLinearMap_surjective {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    Function.Surjective (preparedGermDivisionRemainderLinearMap a ha ha0) := by
  intro r
  refine ⟨remainderPolynomialGerm r, ?_⟩
  have hdivision : IsPreparedGermDivision a ha (remainderPolynomialGerm r)
      0 r := by
    simp [IsPreparedGermDivision]
  exact (preparedGermDivision_eq_of_isDivision a ha ha0
    (remainderPolynomialGerm r) 0 r hdivision).2

end Transformer.RealAnalyticGerms
