/-
# Real analytic germs: PreparedQuotient

Adapted from Bochao Kong's LocalComplexGeometry, revision
029697242294aea7989bf5d391199696a43490df, FiniteProjection/PreparedQuotient.lean.
The coefficient field and analytic germs are real. Only the required
dependency closure is retained. Apache-2.0 license:
third_party/LocalComplexGeometry/LICENSE.
-/

import Transformer.RealAnalyticGerms.Division
import Mathlib.LinearAlgebra.Isomorphisms
import Mathlib.LinearAlgebra.Quotient.Basic
import Mathlib.LinearAlgebra.StdBasis
import Mathlib.RingTheory.Ideal.Quotient.Operations

open Filter
open scoped BigOperators Topology

noncomputable section
namespace Transformer.RealAnalyticGerms

open Transformer.AnalyticPreparation

/-- The principal ideal generated by a fixed prepared polynomial germ.
Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
def preparedPolynomialIdeal {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0) :
    Ideal (AnalyticGerm (n + 1)) :=
  Ideal.span ({preparedPolynomialGerm a ha} : Set (AnalyticGerm (n + 1)))

/-- Assemble a degree-`< d` polynomial from its coefficient vector, as a
base-linear map.
Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
def remainderPolynomialGermLinearMap (n d : ℕ) :
    (Fin d → AnalyticGerm n) →ₗ[AnalyticGerm n]
      AnalyticGerm (n + 1) where
  toFun := remainderPolynomialGerm
  map_add' := remainderPolynomialGerm_add
  map_smul' := remainderPolynomialGerm_smul

/-- Remainder descends to the quotient by the prepared polynomial.
Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
def preparedQuotientRemainderLinearMap {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    (AnalyticGerm (n + 1) ⧸ preparedPolynomialIdeal a ha) →ₗ[AnalyticGerm n]
      (Fin d → AnalyticGerm n) := by
  let rem := preparedGermDivisionRemainderLinearMap a ha ha0
  let I := preparedPolynomialIdeal a ha
  have hle : I.restrictScalars (AnalyticGerm n) ≤ LinearMap.ker rem := by
    rw [preparedGermDivisionRemainderLinearMap_ker a ha ha0]
    rfl
  exact (I.restrictScalars (AnalyticGerm n)).liftQ rem hle |>.comp
    (Submodule.Quotient.restrictScalarsEquiv
      (AnalyticGerm n) I).symm.toLinearMap

/-- Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
@[simp]
theorem preparedQuotientRemainderLinearMap_mk {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (h : AnalyticGerm (n + 1)) :
    preparedQuotientRemainderLinearMap a ha ha0
        (Ideal.Quotient.mk (preparedPolynomialIdeal a ha) h) =
      preparedGermDivisionRemainder a ha ha0 h := by
  rfl

/-- The inverse map sends a coefficient vector to the class of its remainder
polynomial.
Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
def preparedQuotientRemainderSection {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0) :
    (Fin d → AnalyticGerm n) →ₗ[AnalyticGerm n]
      (AnalyticGerm (n + 1) ⧸ preparedPolynomialIdeal a ha) :=
  (Ideal.Quotient.mkₐ (AnalyticGerm n)
      (preparedPolynomialIdeal a ha)).toLinearMap.comp
    (remainderPolynomialGermLinearMap n d)

/-- Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
@[simp]
theorem preparedQuotientRemainderSection_apply {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (r : Fin d → AnalyticGerm n) :
    preparedQuotientRemainderSection a ha r =
      Ideal.Quotient.mk (preparedPolynomialIdeal a ha)
        (remainderPolynomialGerm r) :=
  rfl

/-- Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
@[simp]
theorem preparedGermDivisionRemainder_remainderPolynomialGerm {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (r : Fin d → AnalyticGerm n) :
    preparedGermDivisionRemainder a ha ha0 (remainderPolynomialGerm r) = r := by
  have hdivision : IsPreparedGermDivision a ha (remainderPolynomialGerm r) 0 r := by
    simp [IsPreparedGermDivision]
  exact (preparedGermDivision_eq_of_isDivision a ha ha0
    (remainderPolynomialGerm r) 0 r hdivision).2

/-- Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
theorem preparedQuotientRemainder_rightInverse {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    (preparedQuotientRemainderLinearMap a ha ha0).comp
        (preparedQuotientRemainderSection a ha) = LinearMap.id := by
  ext r
  simp

/-- Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
theorem preparedQuotientRemainder_leftInverse {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    (preparedQuotientRemainderSection a ha).comp
        (preparedQuotientRemainderLinearMap a ha ha0) = LinearMap.id := by
  apply LinearMap.ext
  intro x
  obtain ⟨h, rfl⟩ := Ideal.Quotient.mk_surjective x
  have hspec := preparedGermDivision_spec a ha ha0 h
  unfold IsPreparedGermDivision at hspec
  simp only [LinearMap.comp_apply, preparedQuotientRemainderLinearMap_mk,
    preparedQuotientRemainderSection_apply, LinearMap.id_apply]
  have hpzero : Ideal.Quotient.mk (preparedPolynomialIdeal a ha)
      (preparedPolynomialGerm a ha) = 0 := by
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    exact Ideal.mem_span_singleton_self _
  calc
    Ideal.Quotient.mk (preparedPolynomialIdeal a ha)
        (remainderPolynomialGerm
          (preparedGermDivisionRemainder a ha ha0 h)) =
      Ideal.Quotient.mk (preparedPolynomialIdeal a ha)
        (preparedGermDivisionQuotient a ha ha0 h * preparedPolynomialGerm a ha +
          remainderPolynomialGerm
            (preparedGermDivisionRemainder a ha ha0 h)) := by
        simp only [map_add, map_mul, hpzero, mul_zero, zero_add]
    _ = Ideal.Quotient.mk (preparedPolynomialIdeal a ha) h :=
      congrArg (Ideal.Quotient.mk (preparedPolynomialIdeal a ha)) hspec.symm

/-- The quotient by a prepared polynomial, as a base-linear copy of its
degree-`< d` coefficient vectors.
Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
def preparedQuotientRemainderEquiv {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    (AnalyticGerm (n + 1) ⧸ preparedPolynomialIdeal a ha) ≃ₗ[AnalyticGerm n]
      (Fin d → AnalyticGerm n) :=
  LinearEquiv.ofLinearMap
    (preparedQuotientRemainderLinearMap a ha ha0)
    (preparedQuotientRemainderSection a ha)
    (preparedQuotientRemainder_rightInverse a ha ha0)
    (preparedQuotientRemainder_leftInverse a ha ha0)

/-- Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
@[simp]
theorem preparedQuotientRemainderEquiv_mk {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (h : AnalyticGerm (n + 1)) :
    preparedQuotientRemainderEquiv a ha ha0
        (Ideal.Quotient.mk (preparedPolynomialIdeal a ha) h) =
      preparedGermDivisionRemainder a ha ha0 h :=
  rfl

/-- Auxiliary for Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
@[simp]
theorem preparedQuotientRemainderEquiv_symm_apply {n d : ℕ}
    (a : Fin d → Base n → ℝ) (ha : ∀ i, AnalyticAt ℝ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (r : Fin d → AnalyticGerm n) :
    (preparedQuotientRemainderEquiv a ha ha0).symm r =
      Ideal.Quotient.mk (preparedPolynomialIdeal a ha)
        (remainderPolynomialGerm r) := by
  rfl


end Transformer.RealAnalyticGerms
