/-
# A concrete kernel witness for the Noetherian remainder argument

Taking the constant coefficient of an actual real polynomial has kernel
generated by `X`. Auxiliary example for Appendix D.1, `lem: loj`, of
arXiv:2510.22026v2.
-/

import Transformer.RealAnalyticGerms.NoetherianRemainder
import Mathlib.Algebra.Polynomial.Div
import Mathlib.Algebra.Polynomial.AlgebraMap
import Mathlib.RingTheory.PrincipalIdealDomain

open Polynomial

noncomputable section
namespace Transformer.RealAnalyticGerms

/-- The constant-coefficient remainder map and the proper ideal `(X)`
jointly satisfy the hypotheses of the finite-generation argument.
Appendix D.1, `lem: loj`, of arXiv:2510.22026v2. -/
example : ∃ (I : Ideal ℝ[X]) (p : ℝ[X]) (rem : ℝ[X] →ₗ[ℝ] ℝ),
    p ≠ 0 ∧ p ∈ I ∧
      LinearMap.ker rem ≤ (Ideal.span ({p} : Set ℝ[X])).restrictScalars ℝ ∧ I.FG := by
  let I : Ideal ℝ[X] := Ideal.span ({Polynomial.X} : Set ℝ[X])
  let rem : ℝ[X] →ₗ[ℝ] ℝ := Polynomial.lcoeff ℝ 0
  have hp : (Polynomial.X : ℝ[X]) ∈ I := Ideal.subset_span (Set.mem_singleton _)
  have hker : LinearMap.ker rem ≤ I.restrictScalars ℝ := by
    intro f hf
    apply Ideal.mem_span_singleton.mpr
    exact Polynomial.X_dvd_iff.mpr hf
  exact ⟨I, Polynomial.X, rem, Polynomial.X_ne_zero, hp, hker,
    Ideal.fg_of_remainder_kernel (R := ℝ) (M := ℝ) I Polynomial.X hp rem hker⟩

end Transformer.RealAnalyticGerms
