/-
# Genuine vector Gaussian increments independent of the joint past

arXiv:2506.12543v1, Section 4.3, equations (2)--(3), Theorem 1.
The product law and the full natural-filtration independence are both
proved from the constructed Brownian coordinates.
-/

import Transformer.BatchSize.Section4_BrownianMoments
import Transformer.BatchSize.Section4_VectorGaussianIdentity

open MeasureTheory ProbabilityTheory
open scoped NNReal

noncomputable section

namespace Transformer.BatchSize

/-- The actual vector increment of Section 4.3's independent Brownian
coordinates, before the diagonal amplitude transformation. -/
def vectorBrownianIncrement (d : ℕ) (s t : ℝ≥0) (ω : BrownianSample d) : Fin d → ℝ :=
  fun k => brownianIncrement k s t ω

/-- The actual vector increment is measurable, Section 4.3 (2)--(3). -/
theorem vectorBrownianIncrement_measurable (d : ℕ) (s t : ℝ≥0) :
    Measurable (vectorBrownianIncrement d s t) :=
  Measurable.of_eval fun k => (coordinateBrownian_measurable k t).sub
    (coordinateBrownian_measurable k s)

/-- The genuine law of a forward vector Brownian increment is the
product of independent centered Gaussians with variance t-s,
Section 4.3 (2)--(3). -/
theorem vectorBrownianIncrement_hasLaw (d : ℕ) (s t : ℝ≥0) (hst : s ≤ t) :
    HasLaw (vectorBrownianIncrement d s t)
      (Measure.pi (fun _ : Fin d => gaussianReal 0 (t - s))) (brownianNoiseLaw d) := by
  refine ⟨(vectorBrownianIncrement_measurable d s t).aemeasurable, ?_⟩
  change (Measure.pi (fun _ : Fin d => gaussianLimit)).map
    (fun ω k => brownian t (ω k) - brownian s (ω k)) = _
  rw [Measure.pi_map_pi (f := fun _ : Fin d => fun ω => brownian t ω - brownian s ω)
    (fun _ => ((measurable_brownian t).sub (measurable_brownian s)).aemeasurable)]
  have hvar : nndist (t : ℝ) (s : ℝ) = t - s := by
    apply NNReal.coe_injective
    simp only [coe_nndist, Real.dist_eq, NNReal.coe_sub hst,
      abs_of_nonneg (sub_nonneg.mpr (NNReal.coe_le_coe.mpr hst))]
  congr 1
  funext k
  have h : gaussianLimit.map (fun ω => brownian t ω - brownian s ω) =
      gaussianReal 0 (nndist (t : ℝ) (s : ℝ)) :=
    (isBrownianReal_brownian.toIsPreBrownianReal.hasLaw_sub t s).map_eq
  rw [h, hvar]

/-- The rescaled standard innovation has exactly the forward vector
Brownian law, Section 4.3 (2)--(3), also when elapsed time is zero. -/
theorem standardGaussianVector_rescale_hasLaw (d : ℕ) (r : ℝ≥0) :
    HasLaw (fun z : Fin d → ℝ => fun k => Real.sqrt (r : ℝ) * z k)
      (Measure.pi (fun _ : Fin d => gaussianReal 0 r)) (standardGaussianVectorLaw d) := by
  refine ⟨(Measurable.of_eval fun k => measurable_const.mul (measurable_pi_apply k)).aemeasurable, ?_⟩
  change (Measure.pi (fun _ : Fin d => gaussianReal 0 1)).map
    (fun z k => Real.sqrt (r : ℝ) * z k) = _
  rw [Measure.pi_map_pi (f := fun _ : Fin d => fun z : ℝ => Real.sqrt (r : ℝ) * z)
    (fun _ => (measurable_const.mul measurable_id).aemeasurable)]
  simp_rw [(gaussianFlow_hasLaw (r : ℝ) r.coe_nonneg).map_eq, Real.toNNReal_coe]

/-- The joint natural filtration is contained in the sigma-algebra
generated by the entire coordinate past, Section 4.3 (2)--(3). -/
theorem brownianFiltration_le_comap_past (d : ℕ) (s : ℝ≥0) :
    brownianFiltration d s ≤ MeasurableSpace.comap
      (fun (ω : BrownianSample d) k (u : Set.Iic s) => coordinateBrownian k u ω) inferInstance := by
  change (⨆ u ≤ s, MeasurableSpace.comap (vectorBrownian d u) inferInstance) ≤ _
  refine iSup_le fun u => iSup_le fun hu => ?_
  let past : BrownianSample d → Fin d → Set.Iic s → ℝ :=
    fun ω k r => coordinateBrownian k r ω
  let pick : (Fin d → Set.Iic s → ℝ) → EucSpace d :=
    fun p => WithLp.toLp 2 (fun k => p k ⟨u, hu⟩)
  have hpick : Measurable pick := by
    apply (PiLp.continuousLinearEquiv 2 ℝ (fun _ : Fin d => ℝ)).symm.continuous.measurable.comp
    exact Measurable.of_eval fun k =>
      (measurable_pi_apply (⟨u, hu⟩ : Set.Iic s)).comp (measurable_pi_apply k)
  rw [show vectorBrownian d u = pick ∘ past from rfl, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono (Measurable.comap_le hpick)

/-- The full future vector increment is independent of the entire
natural filtration at its left endpoint, Section 4.3 (2)--(3). -/
theorem vectorBrownianIncrement_indep_filtration (d : ℕ) (s t : ℝ≥0) (hst : s ≤ t) :
    Indep (MeasurableSpace.comap (vectorBrownianIncrement d s t) inferInstance)
      (brownianFiltration d s) (brownianNoiseLaw d) := by
  have hm : Measurable (fun p : Fin d → ℝ≥0 → ℝ => fun k => p k (t - s)) :=
    Measurable.of_eval fun k => (measurable_pi_apply (t - s)).comp (measurable_pi_apply k)
  have hi := (vectorBrownian_future_past_independent d s).comp
    (φ := fun p : Fin d → ℝ≥0 → ℝ => fun k => p k (t - s)) (ψ := id) hm measurable_id
  simp only [Function.comp_def, id_eq, add_tsub_cancel_of_le hst] at hi
  exact indep_of_indep_of_le_right ((IndepFun_iff_Indep _ _ _).mp hi)
    (brownianFiltration_le_comap_past d s)

/-- Any jointly adapted random parameter is independent of the full
next vector increment, Section 4.3 (2)--(3). In particular it can bundle
the current state, all coefficients and a bounded past observable. -/
theorem vectorBrownianIncrement_independent_adapted {d : ℕ} {E : Type*}
    [TopologicalSpace E] [TopologicalSpace.PseudoMetrizableSpace E] [MeasurableSpace E] [BorelSpace E]
    (s t : ℝ≥0) (hst : s ≤ t) {H : BrownianSample d → E}
    (hH : StronglyMeasurable[brownianFiltration d s] H) :
    IndepFun H (vectorBrownianIncrement d s t) (brownianNoiseLaw d) := by
  apply (IndepFun_iff_Indep _ _ _).mpr
  exact (indep_of_indep_of_le_right (vectorBrownianIncrement_indep_filtration d s t hst)
    (Measurable.comap_le hH.measurable)).symm

/-- Joint nonvacuity of the ordered adapted-parameter hypotheses,
Section 4.3: a genuine vector Brownian state at a positive past time. -/
example : (1 : ℝ≥0) ≤ 2 ∧
    StronglyMeasurable[brownianFiltration 2 1] (vectorBrownian 2 1) :=
  ⟨by norm_num, Filtration.stronglyAdapted_natural
    (fun t => (vectorBrownian_measurable 2 t).stronglyMeasurable) 1⟩

end Transformer.BatchSize
