import Transformer.Grokking.CircuitEfficiency.SectionC_TableLoss
import Transformer.Grokking.CircuitEfficiency.SectionC_SubweightGradient
import Transformer.Grokking.CircuitEfficiency.SectionC_SubweightDynamics
import Transformer.Grokking.CircuitEfficiency.SectionC_AdaptiveFirstStep
import Transformer.Grokking.CircuitEfficiency.SectionC_SeedRateComparison
import Transformer.Grokking.CircuitEfficiency.SectionC_NativeSymmetry
import Transformer.Grokking.CircuitEfficiency.SectionC_NativeHistory
import Transformer.Grokking.CircuitEfficiency.SectionC_NativeZero
import Transformer.Grokking.CircuitEfficiency.SectionC_NativeDescent
import Transformer.Grokking.CircuitEfficiency.SectionC_NativeGradientLimits
import Transformer.Grokking.CircuitEfficiency.SectionC_NativeLimitBalance
import Transformer.Grokking.CircuitEfficiency.SectionC_NativeScoreGrowth
import Transformer.Grokking.CircuitEfficiency.SectionC_NativeCELimits
import Transformer.Grokking.CircuitEfficiency.SectionC_NativePositiveBalance
import Transformer.Grokking.CircuitEfficiency.SectionC_NativeUnitPath
import Transformer.Grokking.CircuitEfficiency.SectionC_NativePositiveLimits
import Transformer.Grokking.CircuitEfficiency.SectionC_PhysicalGain
import Transformer.Grokking.CircuitEfficiency.SectionC_GainGradient
import Transformer.Grokking.CircuitEfficiency.SectionD_CEBudgetBasic
import Transformer.Grokking.CircuitEfficiency.SectionD_CEExistence
import Transformer.Grokking.CircuitEfficiency.SectionD_CEMinima
import Transformer.Grokking.CircuitEfficiency.SectionD_EfficientAllocation
import Transformer.Grokking.CircuitEfficiency.SectionD_PowerDerivative
import Transformer.Grokking.CircuitEfficiency.SectionD_SuperlinearAllocation

/-! Fixed-circuit competition in Varma et al., arXiv:2309.02390v1,
with corrected increment estimates, both two-circuit allocation regimes,
explicit penalty/optimum premises and limits of optimizer transfer.
The closed clipped native CE iteration proves positive-factor formation
and a retained symmetry obstruction, separately from coupled penalties. -/
