/-
# Gated fully connected attention model

Ergen, Neyshabur, Mehta, arXiv:2211.11052v1, §3.4, Theorem 3
(`theo:attn_multihead_convex_vector_fcn`), and Appendix A.6.

The source's displayed nonconvex prediction has an unbound head index after
the sum, and its value weight is typed in `ℝ^c` although the input has
embedding dimension `d`.  The appendix makes the intended per-head gated
prediction clear; that version is formalized here.  The printed equivalence
still fails at one head, even with a gate that is always open.
-/

import Transformer.Convexifying.Section3_Vector

open scoped BigOperators

namespace Transformer.Convexifying

/-- The fixed indicator in §3.4: the gate is determined by fixed vectors
`u₁` and `u₂`, independently of the trainable attention weights. -/
noncomputable def gateFromWitness {N h n d : ℕ} (X : Data N n d)
    (u₁ : Fin h → Vec n) (u₂ : Fin h → Vec d)
    (i : Fin N) (j : Fin h) : ℝ :=
  if 0 ≤ ∑ k, u₁ j k * (∑ q, X i k q * u₂ j q) then 1 else 0

/-- The intended gated prediction in equation (13) and Appendix A.6. -/
def gatedPrediction {N h n d c : ℕ} (X : Data N n d)
    (gate : Fin N → Fin h → ℝ) (p : VectorParameters h n d c)
    (i : Fin N) : Vec c :=
  fun l => ∑ j, gate i j *
    scalarHead (X i) (p.attention j) (p.value j) (p.output j l)

/-- The original objective of equation (13), interpreted with one output
term per head as in Appendix A.6. -/
noncomputable def gatedObjective {N h n d c : ℕ} (X : Data N n d)
    (y : Fin N → Vec c) (L : Vec c → Vec c → ℝ) (β : ℝ)
    (gate : Fin N → Fin h → ℝ) (p : VectorParameters h n d c) : ℝ :=
  (∑ i, L (gatedPrediction X gate p i) (y i)) +
    β / 2 * ∑ j, (normSq (p.value j) + (norm₁ (p.output j)) ^ 2)

/-- The convex objective of equation (14), with one matrix for each gate and
output coordinate. -/
noncomputable def gatedConvexObjective {N h n d c : ℕ} (X : Data N n d)
    (y : Fin N → Vec c) (L : ℝ → ℝ → ℝ) (β : ℝ)
    (gate : Fin N → Fin h → ℝ) (Z : Fin h → Fin c → Fin n → Vec d) : ℝ :=
  (∑ i, ∑ l,
    L (∑ j, gate i j * convexPrediction (X i) (Z j l)) (y i l)) +
    β * ∑ l, ∑ j, ∑ k, norm₂ (Z j l k)

/-- Zero gate witnesses open every gate, since the threshold uses `≥ 0`. -/
theorem zeroWitness_opens_gate {N h n d : ℕ} (X : Data N n d)
    (i : Fin N) (j : Fin h) :
    gateFromWitness X (fun _ _ => 0 : Fin h → Vec n)
      (fun _ _ => 0 : Fin h → Vec d) i j = 1 := by
  simp [gateFromWitness]

private def openGate : Fin 2 → Fin 1 → ℝ := fun _ _ => 1

private noncomputable def zeroWitnessGate : Fin 2 → Fin 1 → ℝ :=
  gateFromWitness separatingData (fun _ _ => 0 : Fin 1 → Vec 2)
    (fun _ _ => 0 : Fin 1 → Vec 1)

/-- With a single open gate, the FCN objective is the vector objective. -/
private theorem oneOpenGate_objective (p : VectorParameters 1 2 1 1) :
    gatedObjective separatingData separatingVectorTargets oneOutputSquareLoss
      (1 / 8) openGate p =
    vectorObjective separatingData separatingVectorTargets oneOutputSquareLoss
      (1 / 8) p := by
  have heq : ∀ i : Fin 2,
      gatedPrediction separatingData openGate p i =
        vectorPrediction (separatingData i) p := by
    intro i
    funext l
    simp [gatedPrediction, vectorPrediction, openGate]
  simp only [gatedObjective, vectorObjective]
  simp [heq]

/-- With a single open gate, the convex FCN witness is the vector witness. -/
private theorem oneOpenGate_convex_value :
    gatedConvexObjective separatingData separatingVectorTargets squareLoss
      (1 / 8) openGate
      (fun _ : Fin 1 => fun _ : Fin 1 => separatingWeights) = 1 / 4 := by
  simpa [gatedConvexObjective, vectorConvexObjective, openGate] using
    oneHead_vector_convex_value

/-- **Counterexample to Theorem 3 as stated.**  A gate generated by fixed
zero witnesses is open on every sample, so the one-head counterexample to
Theorem 2 applies verbatim to the gated model.  In particular the number of
convex matrices per gate cannot be represented by one trainable head.
Source: arXiv:2211.11052v1, §3.4, `theo:attn_multihead_convex_vector_fcn`. -/
theorem gated_equivalence_false_for_one_head :
    ¬ ∀ r : ℝ,
      (∃ p : VectorParameters 1 2 1 1,
        p.Feasible ∧
          gatedObjective separatingData separatingVectorTargets
            oneOutputSquareLoss (1 / 8) zeroWitnessGate p ≤ r) ↔
      (∃ Z : Fin 1 → Fin 1 → Fin 2 → Vec 1,
        gatedConvexObjective separatingData separatingVectorTargets
          squareLoss (1 / 8) zeroWitnessGate Z ≤ r) := by
  intro h
  have hgate : zeroWitnessGate = openGate := by
    funext i j
    exact zeroWitness_opens_gate separatingData i j
  rw [hgate] at h
  obtain ⟨p, hp, hbound⟩ := (h (1 / 2)).2
    ⟨fun _ _ => separatingWeights, by rw [oneOpenGate_convex_value]; norm_num⟩
  rw [oneOpenGate_objective] at hbound
  have hlower := oneHead_vector_lower_bound p hp
  linarith

end Transformer.Convexifying
