import Transformer.Grokking.AdamW.MomentSquare

/-!
# Initialized native moment-square history budgets

Source: PyTorch 2.14.1 non-AMSGrad AdamW, adam.py lines 445--475
and 529--547, ported at 88aa892/0033b1b. Both buffers start at zero
and consume the same arbitrary actual gradients. The completed
clock n means that exactly inputs 0 through n-1 have been inserted.

The numerical budget K*(1-(beta1^2/beta2)^n) refines the constant
coupled square guard. Its first value and successor recurrence are
derived explicitly, then native insertions generate the entire
history bound. No present or future buffer inequality is an input
to that initialized history theorem. No gradient bound, sign,
convergence or independence is assumed.

The correction-factor inequality keeps both native bias corrections
at every finite clock. Its algebraic source is the squared difference
of two nonnegative powers whose product is beta1^(2*n). This prepares
the corrected-direction ceiling; it is not a generalization theorem.
The retained optimizer, clipping and gradient stream are unchanged.
No floating-point equivalence or learned transformer convergence is
asserted by these exact-real numerical recurrence estimates.
-/

namespace Transformer.Grokking.AdamW

/-- Numerical zero-initialized finite-clock square budget. Source:
native coupled insertions at 88aa892/0033b1b; each beta and clock
enters the coefficient. It is not a trajectory-success predicate. -/
noncomputable def nativeHistorySquareBudget (b1 b2 : ℝ) (n : ℕ) : ℝ :=
  nativeMomentSquareScale b1 b2 * (1 - (b1 ^ 2 / b2) ^ n)

/-- A positive completed clock has a positive finite-history budget.
Source: native insertions at 88aa892; strict square-memory separation
is an explicit numerical hypothesis, not a stability conclusion. -/
theorem native_history_square_budget_pos (b1 b2 : ℝ) (n : ℕ)
    (h1 : b1 < 1) (h2 : b2 < 1) (hgap : b1 ^ 2 < b2) (hn : 0 < n) :
    0 < nativeHistorySquareBudget b1 b2 n := by
  have hb2 : 0 < b2 := by nlinarith only [hgap, sq_nonneg b1]
  have hr : 0 ≤ b1 ^ 2 / b2 := div_nonneg (sq_nonneg b1) (le_of_lt hb2)
  have hr1 : b1 ^ 2 / b2 < 1 := (div_lt_iff₀ hb2).mpr (by simpa using hgap)
  have hp := pow_lt_one₀ hr hr1 (Nat.ne_of_gt hn)
  exact mul_pos (native_moment_square_scale_pos b1 b2 h1 h2 hgap) (by linarith only [hp])

example : (9 / 10 : ℝ) < 1 ∧ (49 / 50 : ℝ) < 1 ∧
    (9 / 10 : ℝ) ^ 2 < 49 / 50 ∧ 0 < (3 : ℕ) := by norm_num

/-- The first clock has the exact one-gradient square budget.
Source: zero native buffers at 88aa892; this value accounts for
both original smoothing coefficients instead of resetting them. -/
theorem native_history_square_budget_first (b1 b2 : ℝ)
    (h2 : b2 < 1) (hgap : b1 ^ 2 < b2) :
    nativeHistorySquareBudget b1 b2 1 = (1 - b1) ^ 2 / (1 - b2) := by
  have hb2 : 0 < b2 := by nlinarith only [hgap, sq_nonneg b1]
  have hg : b2 - b1 ^ 2 ≠ 0 := by linarith only [hgap]
  have he : 1 - b2 ≠ 0 := by linarith only [h2]
  unfold nativeHistorySquareBudget nativeMomentSquareScale
  rw [pow_one]
  field_simp [ne_of_gt hb2, hg, he]

example : (49 / 50 : ℝ) < 1 ∧ (9 / 10 : ℝ) ^ 2 < 49 / 50 := by norm_num

/-- Every next budget follows the coefficient generated by the
actual shared-input square insertion. Source: native buffers at
88aa892 and MomentSquare.native_moment_square_budget_insert. -/
theorem native_history_square_budget_succ (b1 b2 : ℝ) (n : ℕ)
    (h2 : b2 < 1) (hgap : b1 ^ 2 < b2) :
    nativeHistorySquareBudget b1 b2 (n + 1) =
      b1 ^ 2 * nativeHistorySquareBudget b1 b2 n / b2 + (1 - b1) ^ 2 / (1 - b2) := by
  have hb2 : 0 < b2 := by nlinarith only [hgap, sq_nonneg b1]
  have hg : b2 - b1 ^ 2 ≠ 0 := by linarith only [hgap]
  have he : 1 - b2 ≠ 0 := by linarith only [h2]
  unfold nativeHistorySquareBudget
  rw [pow_succ (b1 ^ 2 / b2) n]
  generalize (b1 ^ 2 / b2) ^ n = history
  unfold nativeMomentSquareScale
  field_simp [ne_of_gt hb2, hg, he]
  ring

example : (49 / 50 : ℝ) < 1 ∧ (9 / 10 : ℝ) ^ 2 < 49 / 50 := by norm_num

/-- Zero native buffers generate the finite-history coupled square
bound for every arbitrary input sequence and completed clock.
Source: native causal recurrences at 88aa892/0033b1b; neither
gradient magnitude nor a future buffer guard is a hypothesis. -/
theorem native_initialized_history_square (b1 b2 : ℝ) (gradient : ℕ → ℝ)
    (h1 : b1 < 1) (h2 : b2 < 1) (hgap : b1 ^ 2 < b2) :
    ∀ n, firstMomentAt b1 gradient n ^ 2 ≤
      nativeHistorySquareBudget b1 b2 n * secondMomentAt b2 gradient n := by
  have hb2 : 0 < b2 := by nlinarith only [hgap, sq_nonneg b1]
  have he : 1 - b2 ≠ 0 := by linarith only [h2]
  intro n
  induction n with
  | zero => simp [firstMomentAt, secondMomentAt, momentAt, nativeHistorySquareBudget]
  | succ n ih =>
    by_cases hn : n = 0
    · subst n
      rw [native_history_square_budget_first b1 b2 h2 hgap]
      simp only [firstMomentAt, secondMomentAt, momentAt, mul_zero, zero_add]
      have hidentity : (1 - b1) ^ 2 / (1 - b2) * ((1 - b2) * gradient 0 ^ 2) =
          ((1 - b1) * gradient 0) ^ 2 := by field_simp [he]
      exact le_of_eq hidentity.symm
    · have hp := native_history_square_budget_pos b1 b2 n h1 h2 hgap (Nat.pos_of_ne_zero hn)
      have ht := native_moment_square_budget_insert b1 b2 (nativeHistorySquareBudget b1 b2 n)
        (firstMomentAt b1 gradient n) (secondMomentAt b2 gradient n) (gradient n) hp hb2 h2 ih
      rw [← native_history_square_budget_succ b1 b2 n h2 hgap] at ht
      exact ht

example : (9 / 10 : ℝ) < 1 ∧ (49 / 50 : ℝ) < 1 ∧ (9 / 10 : ℝ) ^ 2 < 49 / 50 := by norm_num

/-- Actual scalar native paths inherit the initialized finite-clock
square budget from their generated moment histories. Source:
retained state recurrence at 88aa892; only initial zero buffers,
separated smoothing constants and the actual update law are premises. -/
theorem scalar_initialized_history_square (b1 b2 eps decay rate : ℝ)
    (state : ℕ → ScalarState) (gradient : ℕ → ℝ)
    (hstep : ∀ n, state (n + 1) = scalarNativeStep b1 b2 eps decay rate (state n) (gradient n))
    (hm : (state 0).moment = 0) (hv : (state 0).variance = 0)
    (h1 : b1 < 1) (h2 : b2 < 1) (hgap : b1 ^ 2 < b2) :
    ∀ n, (state n).moment ^ 2 ≤ nativeHistorySquareBudget b1 b2 n * (state n).variance := by
  intro n
  have hf := scalar_path_fields b1 b2 eps decay rate state gradient n hstep
  rw [hf.1, hf.2.1, hm, hv]
  exact native_initialized_history_square b1 b2 gradient h1 h2 hgap n

example :
    (∀ n : ℕ, zeroScalarStateAt (n + 1) = scalarNativeStep (9 / 10) (49 / 50) (1 / 100000000)
      (1 / 10) (1 / 1000) (zeroScalarStateAt n) 0) ∧
    (zeroScalarStateAt 0).moment = 0 ∧ (zeroScalarStateAt 0).variance = 0 ∧
    (9 / 10 : ℝ) < 1 ∧ (49 / 50 : ℝ) < 1 ∧ (9 / 10 : ℝ) ^ 2 < 49 / 50 := by
  exact ⟨fun n => (scalar_native_zero_step _ _ _ _ _ n).symm,
    rfl, rfl, by norm_num, by norm_num, by norm_num⟩

/-- Both finite-clock bias corrections are controlled by the exact
history factor. Source: native corrected denominator at 0033b1b;
the geometric coefficient product, not an eventual approximation,
provides the nonnegative squared-difference proof at every clock. -/
theorem native_history_correction_square (b1 b2 : ℝ) (n : ℕ)
    (hb1 : 0 ≤ b1) (hb2 : 0 < b2) :
    (1 - (b1 ^ 2 / b2) ^ n) * (1 - b2 ^ n) ≤ (1 - b1 ^ n) ^ 2 := by
  have hr : 0 ≤ b1 ^ 2 / b2 := div_nonneg (sq_nonneg b1) (le_of_lt hb2)
  have hx := pow_nonneg hr n
  have hy := pow_nonneg (le_of_lt hb2) n
  have hz := pow_nonneg hb1 n
  have hbase : b1 ^ 2 / b2 * b2 = b1 ^ 2 := by field_simp
  have hproduct : (b1 ^ 2 / b2) ^ n * b2 ^ n = (b1 ^ n) ^ 2 := by
    rw [← mul_pow, hbase, ← pow_mul, Nat.mul_comm, pow_mul]
  have ham : 2 * b1 ^ n ≤ (b1 ^ 2 / b2) ^ n + b2 ^ n := by
    nlinarith only [hx, hy, hz, hproduct, sq_nonneg ((b1 ^ 2 / b2) ^ n - b2 ^ n)]
  nlinarith only [ham, hproduct]

example : (0 : ℝ) ≤ 9 / 10 ∧ (0 : ℝ) < 49 / 50 := by norm_num

end Transformer.Grokking.AdamW
