#!/usr/bin/env python3
"""Reproduce arXiv:1912.02292's Lean observations from local author data.

Run with --check to verify the committed Lean tables, or without arguments
to regenerate them. Downloads are separate: papers/ is intentionally ignored.
CSV decimals are represented exactly, without a binary floating point roundtrip.
ResNet observations preserve the exact binary64 values in the NumPy arrays.
The unpickler admits only NumPy data constructors, never arbitrary globals.
"""

import argparse
import csv
import hashlib
import io
from pathlib import Path
import pickle

ROOT = Path(__file__).resolve().parents[1]
PAPERS = ROOT / "papers/arXiv-1912.02292v1"
SRC = ROOT / "src/Transformer/DoubleDescent"


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def csv_rows(filename):
    with (PAPERS / filename).open(newline="") as stream:
        records = list(csv.DictReader(stream))
    rows = [(int(float(row["n"])), row["test_loss"]) for row in records]
    assert all(a[0] < b[0] for a, b in zip(rows, rows[1:]))
    return rows


def table(name, rows, docstring):
    entries = ",\n".join(f"    ⟨{parameter}, {value}⟩" for parameter, value in rows)
    return f"/-- {docstring} -/\ndef {name} : List Observation :=\n  [\n{entries}]\n"


def header(title, filenames, detail):
    fingerprints = "\n".join(f"{name}: {sha256(PAPERS / name)}" for name in filenames)
    return f"""import Transformer.DoubleDescent.Section5_RecordedCurves

/-!
# {title}

arXiv:1912.02292v1. Generated by `scripts/double_descent_data.py` from
the authors' public data at `https://storage.googleapis.com/hml-public/dd/`.
{detail}

Source SHA-256:
{fingerprints}
-/

namespace Transformer.DoubleDescent

"""


def read_numpy_pickle(path):
    import numpy as np

    class DataOnly(pickle.Unpickler):
        def find_class(self, module, name):
            allowed = {
                ("numpy.core.multiarray", "_reconstruct"): np._core.multiarray._reconstruct,
                ("numpy.core.multiarray", "scalar"): np._core.multiarray.scalar,
                ("numpy", "ndarray"): np.ndarray,
                ("numpy", "dtype"): np.dtype,
            }
            if (module, name) not in allowed:
                raise ValueError(f"Unsupported pickle global: {module}.{name}")
            return allowed[module, name]

    return DataOnly(io.BytesIO(path.read_bytes())).load()


def render():
    model_files = ["nlp-model-dd.csv", "dd-translation-model-french.csv"]
    text = header("Published model-wise translation losses", model_files,
                  "Section 5, Figure 8. The notebook plots the `test_loss` column.\n"
                  "Only this column is used; the IWSLT CSV repeats `test_error` in\n"
                  "`train_error`. Neither that field nor these losses measure EMC.")
    text += table("iwsltModelLog", csv_rows(model_files[0]),
                  "Section 5, Figure 8: all 64 recorded IWSLT model sizes and test losses.")
    text += "\n" + table("wmtModelLog", csv_rows(model_files[1]),
                         "Section 5, Figure 8: all 62 recorded WMT model sizes and test losses.")
    model = text + "\nend Transformer.DoubleDescent\n"

    sample_files = ["dd-translation-samples-aug26-small.csv",
                    "dd-translation-samples-aug27-size80.csv"]
    text = header("Published sample-wise translation losses", sample_files,
                  "Section 7, Figure 11(b), and Section 1, Figure 3. Each table\n"
                  "contains every published row for its fixed embedding dimension.\n"
                  "The source calls the plotted loss perplexity; the notebook labels\n"
                  "it cross-entropy. We certify the exported `test_loss` values.")
    for name, filename, dimension in zip(["sample64Log", "sample80Log"], sample_files, [64, 80]):
        with (PAPERS / filename).open(newline="") as stream:
            assert all(float(row["size"]) == dimension for row in csv.DictReader(stream))
        text += table(name, csv_rows(filename),
                      f"Section 7, Figure 11(b): all 59 sample counts at embedding dimension {dimension}.")
        text += "\n"
    sample = text + "end Transformer.DoubleDescent\n"

    epoch_files = ["resnet18-adam-Mlist.pickle", "resnet18-adam-ks.pickle"]
    ms = read_numpy_pickle(PAPERS / epoch_files[0])
    widths = read_numpy_pickle(PAPERS / epoch_files[1])
    assert [int(k) for k in widths] == list(range(1, 65))
    width_index = list(widths).index(64)
    trajectory = ms[1]["Test Error"][width_index]
    assert len(trajectory) == 3999
    selected = [1, 27, 87, 3999]
    rows = []
    for epoch in selected:
        numerator, denominator = float(trajectory[epoch - 1]).as_integer_ratio()
        rows.append((epoch, f"{numerator} / {denominator}"))
    text = header("Published epoch-wise ResNet errors", epoch_files,
                  "Section 6, Figure 10. Extracted from\n"
                  "`dd/cifar10-resnet18k-50k-adam/{Mlist,ks}`: second noise group,\n"
                  "width 64, metric `Test Error`, array positions 0, 26, 86, 3998.\n"
                  "The authors' notebook labels array column j as epoch j+1.\n"
                  "These are four observations, not the entire 3999-column log.")
    text += table("resnetEpochLog", rows,
                  "Section 6: exact stored clean test errors at epochs 1, 27, 87, and 3999.")
    epoch = text + "\nend Transformer.DoubleDescent\n"
    return {"Section5_TranslationLog.lean": model,
            "Section7_TranslationLog.lean": sample,
            "Section6_ResNetLog.lean": epoch}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for filename, content in render().items():
        path = SRC / filename
        if args.check:
            if path.read_text() != content:
                raise SystemExit(f"Mismatch: {path}")
            print(f"Verified {filename}")
        else:
            path.write_text(content)
            print(f"Generated {filename}")


if __name__ == "__main__":
    main()
