#!/usr/bin/env python3
"""Extract exact printed decimals from arXiv:2505.24832v3 Tables 1 and 2."""

from __future__ import annotations

import argparse
from fractions import Fraction
import hashlib
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "papers/arXiv-2505.24832"
TARGET = ROOT / "src/Transformer/Memorization"


def rat(value: Fraction) -> str:
    if value.denominator == 1:
        return str(value.numerator)
    return f"({value.numerator} / {value.denominator})"


def scientific(value: str) -> int:
    match = re.fullmatch(r"\s*([\d.]+)\$\\times10\^\{?(\d+)\}?\$\s*", value)
    if not match:
        raise ValueError(f"Unexpected scientific notation: {value!r}")
    number = Fraction(match[1]) * 10 ** int(match[2])
    assert number.denominator == 1
    return int(number)


def preamble(path: Path, title: str, section: str) -> str:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return f"""import Mathlib.Data.Fin.VecNotation
import Mathlib.Data.Rat.Defs

/-!
# {title}

Generated by `scripts/memorization_data.py`; do not edit by hand.
arXiv:2505.24832v3, {section}.
Source: papers/arXiv-2505.24832/{path.relative_to(PAPER)}
SHA256: {digest}
The rational values represent the printed, rounded measurements exactly;
they are not identified with unknown unrounded experimental values.
-/

namespace Transformer.Memorization

"""


def precision() -> tuple[str, str]:
    path = PAPER / "tables/table05_mem_precision.tex"
    rows = []
    layers = 0
    for line in path.read_text().splitlines():
        layer_match = re.search(r"\\multirow\{4\}\{\*\}\{(\d+)\}", line)
        if layer_match:
            layers = int(layer_match[1])
        row_match = re.match(r"\s*&\s*(\d+)\s*&(.+?)\\\\\s*$", line)
        if not row_match:
            continue
        fields = [field.strip() for field in row_match[2].split("&")]
        assert layers in (1, 2, 4, 8) and len(fields) == 5
        values = [layers, int(row_match[1]), *(scientific(x) for x in fields[:3])]
        values.extend(Fraction(x) for x in fields[3:])
        rows.append("  ⟨" + ", ".join(rat(Fraction(x)) for x in values) + "⟩")
    assert len(rows) == 16
    text = preamble(path, "Printed model-capacity estimates", "Section 3.2, Table 1")
    text += """/-- Section 3.2, Table 1: model configuration and rounded capacity/bpp fields. -/
structure PrecisionObservation where
  layers : ℕ
  width : ℕ
  parameters : ℕ
  fullCapacity : ℕ
  halfCapacity : ℕ
  fullBpp : ℚ
  halfBpp : ℚ

/-- Section 3.2, Table 1: all sixteen model configurations in source order. -/
def precisionTable : Fin 16 → PrecisionObservation := ![
"""
    text += ",\n".join(rows) + "]\n\nend Transformer.Memorization\n"
    return "Section3_PrecisionData.lean", text


def validation() -> tuple[str, str]:
    path = PAPER / "tables/table04_scaling_datasets.tex"
    rows = []
    parameters = 0
    pattern = re.compile(
        r"&\s*([\d,]+)\s*&\s*([\d.]+)\s*&\s*\$([\d.]+)\s*\\pm\s*([\d.]+)\$\s*\\\\"
    )
    for line in path.read_text().splitlines():
        for model_match in re.finditer(r"\\multirow\{3\}\{\*\}\{([\d,]+)\}", line):
            candidate = int(model_match[1].replace(",", ""))
            if candidate > 100_000:
                parameters = candidate
        match = pattern.search(line)
        if not match:
            continue
        assert parameters > 100_000
        values = [Fraction(parameters), Fraction(int(match[1].replace(",", ""))),
                  Fraction(match[2]), Fraction(match[3]) / 100, Fraction(match[4]) / 100]
        rows.append("  ⟨" + ", ".join(rat(x) for x in values) + "⟩")
    assert len(rows) == 6
    text = preamble(path, "Printed membership-inference validation", "Section 5.2.2, Table 2")
    text += """/-- Section 5.2.2, Table 2: the observed percentages and uncertainty are
converted to the same unit interval used by the prediction column.
The table calls the 123,702,528-parameter model GPT2-Medium; its actual
parameter count is retained without adopting that inconsistent label. -/
structure MembershipObservation where
  parameters : ℕ
  datasetSize : ℕ
  predicted : ℚ
  observed : ℚ
  uncertainty : ℚ

/-- Section 5.2.2, Table 2: all six reported validation results. -/
def membershipTable : Fin 6 → MembershipObservation := ![
"""
    text += ",\n".join(rows) + "]\n\nend Transformer.Memorization\n"
    return "Section5_ValidationData.lean", text


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, contents in (precision(), validation()):
        path = TARGET / name
        if args.check:
            if path.read_text() != contents:
                raise SystemExit(f"Source mismatch: {path}")
            print(f"Verified {name}")
        else:
            path.write_text(contents)
            print(f"Wrote {name}")


if __name__ == "__main__":
    main()
