import Transformer.DoubleDescent.Section5_RecordedCurves

/-!
# Published epoch-wise ResNet errors

arXiv:1912.02292v1. Generated by `scripts/double_descent_data.py` from
the authors' public data at `https://storage.googleapis.com/hml-public/dd/`.
Section 6, Figure 10. Extracted from
`dd/cifar10-resnet18k-50k-adam/{Mlist,ks}`: second noise group,
width 64, metric `Test Error`, array positions 0, 26, 86, 3998.
The authors' notebook labels array column j as epoch j+1.
These are four observations, not the entire 3999-column log.

Source SHA-256:
resnet18-adam-Mlist.pickle: 19bfab1371d7fc89192eb029b39c65540cc37ea492a34a24fdf1485eeb7d2660
resnet18-adam-ks.pickle: f282d0739c8afc952996923dd89024cb2fd83392db2cc7f22a6eddb0f519d81c
-/

namespace Transformer.DoubleDescent

/-- Section 6: exact stored clean test errors at epochs 1, 27, 87, and 3999. -/
def resnetEpochLog : List Observation :=
  [
    ⟨1, 1017363155822995 / 2251799813685248⟩,
    ⟨27, 1348377728434727 / 9007199254740992⟩,
    ⟨87, 472427600911165 / 2251799813685248⟩,
    ⟨3999, 291382895890871 / 2251799813685248⟩]

end Transformer.DoubleDescent
