/-
# §6.1, step 2 — the limit lies in the cone of the particles

Geshkovski, Letrouit, Polyanskiy, Rigollet — arXiv:2312.10794v5,
*A mathematical perspective on Transformers*, §6.1, step 2 of
`lem: hemisphere.clustering`.

Step 2 opens with "in view of what precedes we know that `x⋆` lies in the
convex cone generated by the points `x_1(t), …, x_n(t)` for any `t > 0`", and
reads the decomposition `e:decompox*.step2` off it.  The survey gives no
argument for the cone; the one below is step 1 run a second time.  If `x⋆` were
outside the cone, a hyperplane would separate it from the particles at time
`t`: some `w'` with `⟨x_k(t), w'⟩ > 0` for all `k` and `⟨x⋆, w'⟩ ≤ 0`.  Step 1
from time `t` along `w'` keeps every `⟨x_k(s), w'⟩` above a positive floor for
`s ≥ t`, and in the limit `⟨x⋆, w'⟩` is above it too.

The separation is Hahn–Banach between the convex hull `K` of the particles,
which is compact, and the closed ray `{η x⋆ : η ≥ 0}`.  They are disjoint as
soon as no `η ∈ (0,1]` has `η x⋆ ∈ K`: `K` lies in the unit ball, which
excludes `η > 1`, and in the half-space `⟨·, w⟩ > 0` of step 1, which excludes
`η = 0`.
-/

import Transformer.Perspective.Section5_Hemisphere
import Mathlib.Analysis.LocallyConvex.Separation
import Mathlib.Analysis.InnerProductSpace.Dual

open scoped BigOperators

namespace Transformer
namespace Perspective

variable (d n : ℕ)

/-- A time shift of a solution of `SA` is a solution: the equation is
autonomous. -/
theorem SA_shift (β : ℝ) (X : ℝ → SphereTuple d n) (hX : Perspective.SA d n β X) (t : ℝ) :
    Perspective.SA d n β (fun s => X (s + t)) := by
  intro s i
  exact (hX (s + t) i).comp_add_const s t

/-- The minimum `r(t) = min_i ⟨x_i(t), w⟩` of step 1 exists as soon as there
is a particle. -/
theorem exists_isMinInner (hn : 0 < n) (X : ℝ → SphereTuple d n) (w : SSphere d) :
    ∃ r : ℝ → ℝ, IsMinInner d n X w r := by
  have hne : (Finset.univ : Finset (Idx n)).Nonempty := ⟨⟨0, hn⟩, Finset.mem_univ _⟩
  refine ⟨fun t => Finset.univ.inf' hne
    (fun i => inner (𝕜 := ℝ) ((X t i : EucSpace d)) ((w : EucSpace d))), fun t => ⟨?_, ?_⟩⟩
  · exact fun i => Finset.inf'_le _ (Finset.mem_univ i)
  · obtain ⟨i, -, hi⟩ := Finset.exists_mem_eq_inf' hne
      (fun i => inner (𝕜 := ℝ) ((X t i : EucSpace d)) ((w : EucSpace d)))
    exact ⟨i, hi⟩

/-- Step 1 read at the particles: from the hemisphere at time `0` there is a
floor `r₀ > 0` below every `⟨x_i(t), w⟩`, `t ≥ 0`. -/
theorem exists_floor_of_hemisphere (hn : 0 < n)
    (β : ℝ) (w : SSphere d) (X : ℝ → SphereTuple d n) (hX : Perspective.SA d n β X)
    (hinit : ∀ i : Idx n,
      0 < inner (𝕜 := ℝ) ((X 0 i : EucSpace d)) ((w : EucSpace d))) :
    ∃ r₀ : ℝ, 0 < r₀ ∧ ∀ t : ℝ, 0 ≤ t → ∀ i : Idx n,
      r₀ ≤ inner (𝕜 := ℝ) ((X t i : EucSpace d)) ((w : EucSpace d)) := by
  obtain ⟨r, hr⟩ := exists_isMinInner d n hn X w
  have hmono := hemisphere_step1_monotone d n β w X r hX hr hinit
  obtain ⟨i₀, hi₀⟩ := (hr 0).2
  refine ⟨r 0, by rw [hi₀]; exact hinit i₀, fun t ht i => ?_⟩
  exact (hmono (Set.mem_Ici.mpr le_rfl) (Set.mem_Ici.mpr ht) ht).trans ((hr t).1 i)

/-- **The limit of step 1 lies in the cone of the particles.**

If all particles start in the open hemisphere `⟨x, w⟩ > 0` and converge to
`x⋆`, then for every `t ≥ 0` some `η ∈ (0,1]` makes `η x⋆` a convex
combination of `x_1(t), …, x_n(t)`.

The survey asserts this for `t > 0` and `β > 0`; it holds for `t ≥ 0` and
every `β`.  `0 < n` is the survey's standing `n ≥ 1`: with no particle the
convex hull is empty.

Source: arXiv:2312.10794v5, §6.1, step 2 of `lem: hemisphere.clustering`,
before `e:decompox*.step2`. -/
theorem limit_mem_cone (hn : 0 < n)
    (β : ℝ) (w : SSphere d) (X : ℝ → SphereTuple d n) (hX : Perspective.SA d n β X)
    (hinit : ∀ i : Idx n,
      0 < inner (𝕜 := ℝ) ((X 0 i : EucSpace d)) ((w : EucSpace d)))
    (x_star : SSphere d)
    (hlim : ∀ i : Idx n, Filter.Tendsto (fun s => (X s i : EucSpace d)) Filter.atTop
      (nhds (x_star : EucSpace d)))
    (t : ℝ) (ht : 0 ≤ t) :
    ∃ η : ℝ, η ∈ Set.Ioc (0 : ℝ) 1 ∧
      η • (x_star : EucSpace d) ∈
        convexHull ℝ (Set.range fun k : Idx n => ((X t k : EucSpace d))) := by
  set K := convexHull ℝ (Set.range fun k : Idx n => ((X t k : EucSpace d))) with hK
  set R := (fun η : ℝ => η • (x_star : EucSpace d)) '' Set.Ici 0 with hR
  have hxs : ‖(x_star : EucSpace d)‖ = 1 := mem_sphere_zero_iff_norm.mp x_star.2
  by_contra hno
  push Not at hno
  -- every point of `K` has norm at most one and positive inner product with `w`
  obtain ⟨r₀, hr₀, hfloor⟩ := exists_floor_of_hemisphere d n hn β w X hX hinit
  have hKw : K ⊆ {v : EucSpace d | r₀ ≤ inner (𝕜 := ℝ) v ((w : EucSpace d))} := by
    refine convexHull_min ?_ ?_
    · rintro v ⟨k, rfl⟩
      exact hfloor t ht k
    · exact convex_halfSpace_ge
        ⟨fun a b => inner_add_left _ _ _, fun c a => real_inner_smul_left _ _ _⟩ _
  have hKn : K ⊆ Metric.closedBall 0 1 := by
    refine convexHull_min ?_ (convex_closedBall 0 1)
    rintro v ⟨k, rfl⟩
    simp [mem_sphere_zero_iff_norm.mp (X t k).2]
  have hdisj : Disjoint K R := by
    rw [Set.disjoint_left]
    rintro v hvK ⟨η, hη, rfl⟩
    rcases (Set.mem_Ici.mp hη).lt_or_eq with hη0 | hη0
    · rcases le_or_gt η 1 with hη1 | hη1
      · exact hno η ⟨hη0, hη1⟩ hvK
      · have := hKn hvK
        rw [Metric.mem_closedBall, dist_zero_right, norm_smul, hxs, mul_one,
          Real.norm_eq_abs, abs_of_pos hη0] at this
        linarith
    · have := hKw hvK
      simp only [← hη0, zero_smul, Set.mem_ofPred_eq, inner_zero_left] at this
      linarith
  have hKc : IsCompact K := (Set.finite_range _).isCompact_convexHull (𝕜 := ℝ)
  have hRconv : Convex ℝ R :=
    (convex_Ici (0 : ℝ)).linear_image (LinearMap.toSpanSingleton ℝ _ (x_star : EucSpace d))
  have hRclosed : IsClosed R :=
    (isClosedEmbedding_smul_left (𝕜 := ℝ) (ne_zero_of_mem_unit_sphere x_star)).isClosedMap _
      isClosed_Ici
  obtain ⟨f, u, v, hfK, huv, hfR⟩ := geometric_hahn_banach_compact_closed
    (convex_convexHull ℝ _) hKc hRconv hRclosed hdisj
  -- `f` is negative on the particles and non-negative at `x⋆`
  have hv0 : v < 0 := by simpa using hfR 0 ⟨0, Set.mem_Ici.mpr le_rfl, zero_smul ℝ _⟩
  have hfx : 0 ≤ f (x_star : EucSpace d) := by
    by_contra hneg
    push Not at hneg
    have := hfR ((v / f (x_star : EucSpace d)) • (x_star : EucSpace d))
      ⟨v / f (x_star : EucSpace d), div_nonneg_of_nonpos hv0.le hneg.le, rfl⟩
    rw [map_smul, smul_eq_mul, div_mul_cancel₀ _ hneg.ne] at this
    exact lt_irrefl _ this
  set h : EucSpace d := -(InnerProductSpace.toDual ℝ (EucSpace d)).symm f with hhdef
  have hh : ∀ x : EucSpace d, inner (𝕜 := ℝ) x h = - f x := by
    intro x
    rw [hhdef, inner_neg_right, real_inner_comm, InnerProductSpace.toDual_symm_apply]
  have hpos : ∀ k : Idx n, 0 < inner (𝕜 := ℝ) ((X t k : EucSpace d)) h := by
    intro k
    rw [hh]
    have := hfK _ (subset_convexHull ℝ _ ⟨k, rfl⟩)
    linarith
  have hh0 : h ≠ 0 := by
    intro h0
    have := hpos ⟨0, hn⟩
    rw [h0, inner_zero_right] at this
    exact lt_irrefl _ this
  have hnh : 0 < ‖h‖ := norm_pos_iff.mpr hh0
  let w' : SSphere d := ⟨‖h‖⁻¹ • h, by
    rw [mem_sphere_zero_iff_norm, norm_smul, norm_inv, norm_norm, inv_mul_cancel₀ hnh.ne']⟩
  have hw' : ∀ x : EucSpace d, inner (𝕜 := ℝ) x ((w' : EucSpace d)) = ‖h‖⁻¹ * inner (𝕜 := ℝ) x h :=
    fun x => real_inner_smul_right _ _ _
  -- step 1 again, from time `t` and along `w'`
  obtain ⟨r₁, hr₁, hfloor'⟩ := exists_floor_of_hemisphere d n hn β w' (fun s => X (s + t))
    (SA_shift d n β X hX t) (fun k => by
      rw [zero_add, hw']; exact mul_pos (inv_pos.mpr hnh) (hpos k))
  have hlim' : Filter.Tendsto
      (fun s => inner (𝕜 := ℝ) ((X (s + t) ⟨0, hn⟩ : EucSpace d)) ((w' : EucSpace d)))
      Filter.atTop (nhds (inner (𝕜 := ℝ) ((x_star : EucSpace d)) ((w' : EucSpace d)))) :=
    (((hlim ⟨0, hn⟩).comp (Filter.tendsto_atTop_add_const_right _ t
      Filter.tendsto_id)).inner tendsto_const_nhds)
  have hge : r₁ ≤ inner (𝕜 := ℝ) ((x_star : EucSpace d)) ((w' : EucSpace d)) :=
    ge_of_tendsto hlim' (Filter.eventually_atTop.mpr ⟨0, fun s hs => hfloor' s hs _⟩)
  rw [hw', hh] at hge
  nlinarith [inv_pos.mpr hnh]

/-- **Equation (e:decompox*.step2) for the limit of step 1.**

Under the hemisphere hypothesis of `lem: hemisphere.clustering`, the common
limit `x⋆` of the particles is, at every time `t ≥ 0`, a non-negative
combination `x⋆ = Σ_k θ_k(t) x_k(t)` with `Σ_k θ_k(t) ≥ 1`.

Source: arXiv:2312.10794v5, §6.1, `e:decompox*.step2`. -/
theorem step2_decomposition_of_limit (hn : 0 < n)
    (β : ℝ) (w : SSphere d) (X : ℝ → SphereTuple d n) (hX : Perspective.SA d n β X)
    (hinit : ∀ i : Idx n,
      0 < inner (𝕜 := ℝ) ((X 0 i : EucSpace d)) ((w : EucSpace d)))
    (x_star : SSphere d)
    (hlim : ∀ i : Idx n, Filter.Tendsto (fun s => (X s i : EucSpace d)) Filter.atTop
      (nhds (x_star : EucSpace d)))
    (t : ℝ) (ht : 0 ≤ t) :
    ∃ θ : Idx n → ℝ,
      (∀ k, 0 ≤ θ k) ∧ (1 ≤ ∑ k : Idx n, θ k) ∧
        ((x_star : EucSpace d) = ∑ k : Idx n, (θ k) • ((X t k : EucSpace d))) :=
  step2_decomposition d n X x_star t (limit_mem_cone d n hn β w X hX hinit x_star hlim t ht)

/-- The hypotheses of `limit_mem_cone` and `step2_decomposition_of_limit` are
satisfiable: one particle at rest, `w = x⋆` its position. -/
example :
    Perspective.SA 1 1 0 (fun _ _ => basePoint 0) ∧
      (∀ i : Idx 1, 0 < inner (𝕜 := ℝ)
        (((fun _ _ => basePoint 0 : ℝ → SphereTuple 1 1) 0 i : EucSpace 1))
        (((basePoint 0 : SSphere 1)) : EucSpace 1)) ∧
      ∀ i : Idx 1, Filter.Tendsto
        (fun s => (((fun _ _ => basePoint 0 : ℝ → SphereTuple 1 1) s i : EucSpace 1)))
        Filter.atTop (nhds (((basePoint 0 : SSphere 1)) : EucSpace 1)) := by
  have hx : ‖((basePoint 0 : SSphere 1) : EucSpace 1)‖ = 1 :=
    mem_sphere_zero_iff_norm.mp (basePoint 0).2
  refine ⟨Perspective.SA_const_consensus 1 1 one_pos 0 (basePoint 0), fun _ => ?_,
    fun _ => tendsto_const_nhds⟩
  rw [real_inner_self_eq_norm_mul_norm, hx]; norm_num

end Perspective
end Transformer
